#!/bin/bash

#ffmpeg -i inputfile -ss starttime -t duration -vn -codec copy -loglevel quiet outputfile
#audcut starttime stoptime input.mp3/mp4 output.mp3

start=$(date --utc --date "$1" +%s)
 stop=$(date --utc --date "$2" +%s)
  dur=$(date --utc --date "1970-01-01 $[$stop-$start] sec" "+%T")

echo timedur=$dur
ffmpeg -i "$3" -ss "$1" -t "$dur" -vn -codec copy -loglevel quiet "$4"
