#!/bin/bash

cat file1.mp3 file2.mp3 > file.mp3

ffmpeg -i "concat:file1.mp3|file2.mp3" -acodec copy output.mp3

ffmpeg -f concat -safe 0 -i mylist.txt -c copy output.mp3

audio-join() ffmpeg -i "concat:${(j:|:)@[2,-1]}" -acodec copy $1
audio-join output.mp3 *.mp3

ls *.mp3 | sed -e "s/\(.*\)/file '\1'/" | \
    ffmpeg -protocol_whitelist 'file,pipe' -f concat -i - -c copy output.mp3

ffmpeg -f concat -safe 0 \
    -i <(find "$(pwd)" -iname '*.mp3' -printf "file '%p'\n" | sort) -c copy merged.mp3

function join_by { local IFS="$1"; shift; echo "$*"; }
files=(*.mp3)
ffmpeg -i "concat:`join_by "|" $files`" -acodec copy output.mp3
