#!/bin/bash

[[ -z "$1" ]] && exit 1

rate=96
while getopts "r:" opt; do
    case $opt in
        r)
           rate="$OPTARG"
           ;;

        ?) echo 'Usage: audconv [-r rate] <file>'
           exit 1;;
    esac
done

shift $((OPTIND-1))  #This tells getopts to move on to the next argument.

ffmpeg -i "$1" -b:a ${rate}k -loglevel quiet "$1.mp3"
