#!/bin/bash

CMD="mpg321 -q"
while getopts "bB" opt; do
    case $opt in
        b)
            [[ -z "$DISPLAY" ]] && CMD="mplayer" || CMD="mpv 2>/dev/null"
            ;;
        B)
            [[ -z "$DISPLAY" ]] && CMD="mpv --vo=drm 2>/dev/null" || CMD="mplayer -vo x11"
            ;;
        ?)
            echo 'Usage: audplay [-bB] <file>'
            exit 1;;
    esac
done
shift $((OPTIND -1))

if [ $# -gt 1 ] || [ $# -eq 0 ]; then
    echo 'Usage1: audplay [-bB] <file>'
    exit 1
fi

if [ ! -f "$1" ]; then
    echo 'Usage2: audplay [-bB] <file>'
    exit 1
fi

if [[ $CMD =~ "mpg" ]]; then
    tsp $CMD "$1" > /dev/null 2>&1
else
    $CMD "$1" > /dev/null 2>&1
fi

exit 0
