#!/bin/bash

CMD="mpg321 -q"
while getopts "bB" opt; do
    case $opt in
        b)
            CMD="mplayer" ;;
        B)
            CMD="mpv" ;;
        ?)
            echo 'Usage: audplay [-bB] <file>'
            exit 1;;
    esac
done
shift $((OPTIND -1))

if [ $# -gt 1 ] || [ $# -eq 0 ]; then
    echo 'Usage1: audplay [-bB] <file>'
    exit 1
fi

if [ ! -f "$1" ]; then
    echo 'Usage2: audplay [-bB] <file>'
    exit 1
fi

$CMD "$1" > /dev/null 2>&1 &
exit 0
