#!/bin/bash

[[ -z "$DISPLAY" ]] && SID=0 || SID=1
[[ ! "$TERM" =~ "screen" ]] && SID=13    #not in tmux session

tmux list-w | egrep "ranger\*|vifmrun\*" > /dev/null 2>&1
if [ $? -ne 0 ]; then
    exit 0
fi

#xclip -sel clip < /dev/null

tmux send-keys xY

sleep 0.2

tmux select-window -t $SID:1 > /dev/null 2>&1
if [ $? -ne 0 ]; then
    exit 0
fi

tmux send-keys C-u
tmux send-keys "cd $(xclip -o -sel clip)"
tmux send-keys C-m
exit 0
