#!/bin/bash

[[ -z "$DISPLAY" ]] && SID=0 || SID=1
[[ ! "$TERM" =~ "screen" ]] && SID=12    #not in tmux session
#[[ $(tmux ls | egrep "13:.*attached") ]] && SID=13

background=0
while getopts "b" opt; do
    case $opt in
        b)  background=1 ;;

        ?)  echo 'Usage: autocd [-b]'
            exit 1;;
    esac
done
shift $((OPTIND-1))

tmux list-w | egrep "ranger\*|vifm\*|vifmrun\*|nova\*" > /dev/null 2>&1
if [ $? -ne 0 ]; then
    exit 0
fi

tmux send-keys gY
sleep 0.1

#tmux select-window -t $SID:1 > /dev/null 2>&1
#if [ $? -ne 0 ]; then
#    exit 0
#fi

if [ -z "$DISPLAY" ]; then
    tmux send-keys -t $SID:1 C-u
    tmux send-keys -t $SID:1 "cd "
    sleep 0.1
    tmux send-keys -t $SID:1 "$(tmux paste-buffer)"
    tmux send-keys -t $SID:1 C-m
    if [ $background -eq 0 ]; then
        tmux select-window -t $SID:1
    fi
    exit 0
fi

tmux send-keys -t $SID:1 C-u
tmux send-keys -t $SID:1 "cd $(xclip -o -sel clip)"
tmux send-keys -t $SID:1 C-m
if [ $background -eq 0 ]; then
    tmux select-window -t $SID:1
fi
exit 0
