#!/usr/bin/env bash

[[ -z "$DISPLAY" ]] && (tmux paste-buffer; exit 0)

xclip -o | xargs -0 tmux setb && tmux paste-buffer
exit 0

#!/usr/bin/env bash
# AUTHOR: gotbletu (@gmail|twitter|youtube|github|lbry)
#         https://www.youtube.com/user/gotbletu
# DESC:   copy from your clipboard history
# DEMO:   https://www.youtube.com/watch?v=Vzt0tVNrJ0A
# DEPEND: fzf greenclip coreutils xsel (or tmux)
# REFF:   https://github.com/erebe/greenclip
# NOTE:   not good with multiline at the moment
# https://github.com/erebe/greenclip

selected="$(greenclip print | fzf -e -i --reverse)"
[ -z "$selected" ] && exit

# add to tmux and X11 clipboard
printf "%s" "$selected" | xsel -b
printf "%s" "$selected" | tmux load-buffer -
#xsel -b < "$selected"
#tmux load-buffer "$selected"

#curr_name=$(i3-msg -t get_workspaces | jq '.[] | select(.focused==true).name')
#if [ $curr_name =~ "term" ]; then
#    i3-msg exec 'xdotool key ctrl+c'
#    exit 0
#fi
#
#if [ $curr_name =~ "www" ]; then
#    i3-msg exec 'xdotool click 3'
#    i3-msg exec 'xdotool key c'
#fi
