#!/usr/bin/env bash

if [[ -z "$DISPLAY" ]]; then
    tmux paste-buffer
    exit 0
fi

xclip -o | xargs -0 tmux setb && tmux paste-buffer

#curr_name=$(i3-msg -t get_workspaces | jq '.[] | select(.focused==true).name')
#if [ $curr_name =~ "term" ]; then
#    i3-msg exec 'xdotool key ctrl+c'
#    exit 0
#fi
#
#if [ $curr_name =~ "www" ]; then
#    i3-msg exec 'xdotool click 3'
#    i3-msg exec 'xdotool key c'
#fi
