#!/usr/bin/env bash

#curr_name=$(i3-msg -t get_workspaces | jq '.[] | select(.focused==true).name')
#if [ $curr_name =~ "term" ]; then
#    i3-msg exec 'xdotool key ctrl+c'
#    exit 0
#fi
#
#if [ $curr_name =~ "www" ]; then
#    i3-msg exec 'xdotool click 3'
#    i3-msg exec 'xdotool key c'
#fi

xclip -o | xargs -0 tmux setb
#clip=$(xclip -o)
#tmux setb "$clip"
