#! /bin/bash

SESSION=0

if [ ! -z "$DISPLAY" ]; then
    mutt
    exit 0
fi

tmux has-session -t $SESSION
if [ $? -ne 0 ]; then
    mutt
    exit 0
fi

tmux select-window -t mutt > /dev/null 2>&1
if [ $? -ne 0 ]; then
    tmux new-window -n mutt -t $SESSION:5 mutt
fi

exit 0
