#!/bin/bash
# fbtmux: a wrapper script to enable background image with fbterm in tmux (invoked in .bashrc)

# hide the cursor
# echo -ne "\e[?25l"
# setterm -cursor off

if [ ! -z "$DISPLAY" ]; then
    tmux
    exit 0
fi

tmux has-session -t 0
if [ $? -eq 0 ]; then
    exit 0
fi

fbv -ciuker "/home/simone/.wallpaper/desktop-$(date +%d).jpg" << EOF
q
EOF

export FBTERM_BACKGROUND_IMAGE=1
exec fbterm -- tmux > /dev/null 2>&1
#[ x-is-run ] && tmux set status on

exit 0

#fbv -ciuker "$1" << EOF
#q
#EOF
#
#shift
#export FBTERM_BACKGROUND_IMAGE=1
#exec fbterm "$@"
