#!/bin/bash
# fbtmux: a wrapper script to enable background image with fbterm in tmux (invoked in .bashrc)

# hide the cursor
# echo -ne "\e[?25l"
# setterm -cursor off

[[ -z "$DISPLAY" ]] && SID=0  || SID=1
[[ -z "$DISPLAY" ]] && SRV="" || SRV="-L x-serv"
CMD="tmux $SRV new-session -s $SID"

tmux $SRV has-session -t $SID 2>/dev/null
if [ $? -eq 0 ]; then
    exit 0
fi

if [ ! -z "$DISPLAY" ]; then
    $CMD
    exit 0
fi

echo -ne "\e[?25l"  #hide cursor
fbv -ciuker "/home/simone/.wallpaper/desktop-$(date +%d).jpg" << EOF
q
EOF

export FBTERM_BACKGROUND_IMAGE=1
exec fbterm -- $CMD > /dev/null 2>&1

exit 0
