#!/bin/bash

OPTS="-"
while getopts "bB" opt; do
    case $opt in
        b)
            OPTS+="b" ;;
        B)
            OPTS+="B" ;;
        ?)
            echo 'Usage: fileopen [-bB] <file>'
            exit 1;;
    esac
done
shift $((OPTIND-1))  #This tells getopts to move on to the next argument.

if [ $OPTS = "-" ]; then
    OPTS=""
fi

[ $# -eq 0 ] && exit 1

file="$*"
if [[ $* =~ '\' ]]; then
    file=${file// /\\\ }
    file=${file//(/\\\(}
    file=${file//)/\\\)}
fi

#file is directory
if [ -d "$file" ]; then
    nautilus --no-desktop 2>/dev/null "$file" &
    exit 0
fi

#echo $file
if [ ! -f "$file" ]; then
    echo 'Usage1: fileopen [-bB] <file>'
    exit 1
fi

ext="${file##*.}"
ext=$(echo ${ext} | tr '[:upper:]' '[:lower:]')

case "$ext" in
    mp3|wav|flac|ogg|w4a|wma|ape|rm)
        audplay $OPTS "$file" && exit 0
        ;;

    rmvb|rmb|swf|avi|mp4|wmv|3gp|ogv|mkv|mpg|vob|flv|rmvb|rmb|vdat|webm)
        vidplay $OPTS "$file" && exit 0
        ;;

    bmp|jpg|jpeg|png|gif|xpm|ppm|webp)
        imgview $OPTS "$file" && exit 0
        ;;

    gif)
        mpv "$file" && exit 0
        pqiv -f "$file" && exit 0
        vimiv -f "$file" && exit 0
        ;;

    htm|html|xhtml)
        webview $OPTS "$file" && exit 0
        ;;

    pdf|ps)
        pdfview $OPTS "$file" && exit 0
        ;;

    epub)
        if [ -z $DISPLAY ]; then
            epr "$file" && exit 0
        else
            zathura "$file" && exit 0
        fi
        ;;

    djvu)
        if [ -z $DISPLAY ]; then
            fbpdf "$file" && exit 0
            exiftool "$file" && exit 0
        else
            zathura "$file" && exit 0
        fi
        ;;

    tpp)
        tpp "$file" && exit 0
        ;;

    url)
        vimux "$file" && exit 0
esac

filemimetype="$(file --dereference --brief --mime-type -- "${file}")"
case "${filemimetype}" in
    text/*|*/json)
        vimux "$file" && exit 0
        ;;
esac

echo "Open file ($file) failed!"
exit 1
