#! /usr/bin/env bash

SID=0
WID=9
WIN='filemgr'

if [ -z "$DISPLAY" ]; then
    CMD='vifm'
else
    SID=1
    CMD="cd $(< $HOME/.cache/ranger/rangerdir); ranger --choosedir=$HOME/.cache/ranger/rangerdir"
fi

# not in tmux session
if [[ ! "$TERM" =~ "screen" ]]; then
    SID=13
    if [ -z "$DISPLAY" ]; then
        CMD='vifm'
    else
        CMD='ranger --cmd=tab_new'
    fi
fi

while getopts "b" opt; do
    case $opt in
        b)
            if [ -z "$DISPLAY" ]; then
                CMD='cd $(< $HOME/.cache/ranger/rangerdir); ranger --choosedir=$HOME/.cache/ranger/rangerdir'
            else
                CMD='vifm'
            fi
            ;;

        ?)  echo 'Usage: filemgr [-b]'
            exit 1;;
    esac
done

shift $((OPTIND-1))

if [ $# -ne 0 ]; then
    echo 'Usage1: filemgr [-b]'
    exit 1
fi

tmux has-session -t $SID 2>/dev/null
if [ $? -ne 0 ]; then
    $CMD
    exit 0
fi

tmux select-window -t $SID:$WIN > /dev/null 2>&1
if [ $? -ne 0 ]; then
    tmux new-window -n $WIN -t $SID:$WID "stty -ixon; $CMD"

    if [[ "$CMD" =~ "ranger" ]]; then
        #tmux send-keys -t $SID:$WID C-t
        #tmux send-keys -t $SID:$WID Space
        dir2="$(< $HOME/.cache/ranger/rangerdir2)"
        tmux set-buffer ":tab_new $dir2"
        tmux paste-buffer -t $SID:$WID
        tmux send-keys -t $SID:$WID C-m
    fi
fi

exit 0
