#! /usr/bin/env bash

if [ -z "$DISPLAY" ]; then
    SID=0
    CMD='vifm'
else
    SID=1
    CMD="cd $(cat $HOME/.cache/ranger/rangerdir); ranger --choosedir=$HOME/.cache/ranger/rangerdir"
fi

if [ $TERM != "screen" ]; then
    SID=13
    if [ -z "$DISPLAY" ]; then
        CMD='vifm'
    else
        CMD='ranger --cmd=tab_new'
    fi
fi

WID=9
WIN='filemgr'

while getopts "b" opt; do
    case $opt in
        b)
            if [ -z "$DISPLAY" ]; then
                CMD='cd $(cat $HOME/.cache/ranger/rangerdir); ranger --choosedir=$HOME/.cache/ranger/rangerdir'
            else
                CMD='vifm'
            fi
            ;;

        ?)  echo 'Usage: filemgr [-b]'
            exit 1;;
    esac
done

shift $((OPTIND-1))

if [ $# -ne 0 ]; then
    echo 'Usage1: filemgr [-b]'
    exit 1
fi

tmux has-session -t $SID 2>/dev/null
if [ $? -ne 0 ]; then
    $CMD
    exit 0
fi

tmux select-window -t $SID:$WIN > /dev/null 2>&1
if [ $? -ne 0 ]; then
    tmux new-window -n $WIN -t $SID:$WID "stty -ixon; $CMD"
fi

if [[ "$CMD" =~ "ranger" ]]; then
    tmux send-keys -t $SID:$WID C-t
    tmux send-keys -t $SID:$WID Space
fi

exit 0
