#! /usr/bin/env bash

if [ -z "$DISPLAY" ]; then
    SID=0
    CMD='vifm'
else
    SID=1
    CMD='vifmrun'
fi

WID=9
WIN='vifm'

while getopts "b" opt; do
    case $opt in
        b)
            WID=0
            CMD='ranger'
            WIN='ranger'
            ;;

        ?)  echo 'Usage: filemgr [-b]'
            exit 1;;
    esac
done

shift $((OPTIND-1))

if [ $# -ne 0 ]; then
    echo 'Usage1: filemgr [-b]'
    exit 1
fi

tmux has-session -t $SID
if [ $? -ne 0 ]; then
    $CMD
    exit 0
fi

tmux select-window -t $SID:$WIN > /dev/null 2>&1
if [ $? -ne 0 ]; then
    tmux new-window -n $WIN -t $SID:$WID "stty -ixon; $CMD"
fi

exit 0
