#! /bin/bash

shopt -s globstar
shopt -s nocaseglob

fim *.{jpg,jpeg,png,bmp,gif,ppm,xpm} 2> /dev/null

#fim {,**/}*.{jpg,jpeg,png,bmp,gif,ppm,xpm} 2> /dev/null

#find . -maxdepth 1 -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.png' -o -iname '*.bmp' -o -iname '*.gif' | fim -
#find . -maxdepth 1 -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.png' -o -iname '*.bmp' -o -iname '*.gif' -exec fim {} +
#find . -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.png' -o -iname '*.bmp' -o -iname '*.gif' | fim -c 'endless_slideshow' -
#find . -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.png' -o -iname '*.bmp' -o -iname '*.gif' -exec fim -c 'endless_slideshow' {} +
