#! /bin/bash

shopt -s nullglob
shopt -s globstar
shopt -s nocaseglob

flag=$1
show=$2
path=$3

if [ "$flag" != "current" ] && [ "$flag" != "recursive" ]; then
    echo 'Arg1 should be "current" or "recursive"'
    exit 1
fi

if [ "$show" != "normal" ] && [ "$show" != "slideshow" ]; then
    echo 'Arg2 should be "noraml" or "slideshow"'
    exit 1
fi

if [ -n "$path" ]; then
    cd "$path"
fi

if [ "$flag" = "current" ]; then
    if [ "$show" = "normal" ]; then
        fim *.{jpg,jpeg,png,bmp,gif,ppm,xpm} > /dev/null 2>&1
    else
        fim -c 'endless_slideshow' *.{jpg,jpeg,png,bmp,gif,ppm,xpm} > /dev/null 2>&1
    fi
else
    if [ "$show" = "normal" ]; then
        fim {,**/}*.{jpg,jpeg,png,bmp,gif,ppm,xpm} > /dev/null 2>&1
    else
        fim -c 'endless_slideshow' {,**/}*.{jpg,jpeg,png,bmp,gif,ppm,xpm} > /dev/null 2>&1
    fi
fi

exit 0

#find . -maxdepth 1 -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.png' -o -iname '*.bmp' -o -iname '*.gif' | fim -
#find . -maxdepth 1 -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.png' -o -iname '*.bmp' -o -iname '*.gif' -exec fim {} +
#find . -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.png' -o -iname '*.bmp' -o -iname '*.gif' | fim -c 'endless_slideshow' -
#find . -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.png' -o -iname '*.bmp' -o -iname '*.gif' -exec fim -c 'endless_slideshow' {} +
