#! /usr/bin/env bash

SID=0
WID=9

if [ -z "$DISPLAY" ]; then
    CMD='vifm --server-name vifm-tty'
    WIN='vifm'
else
    SID=1
    #CMD="cd $(< $HOME/.cache/ranger/rangerdir); ranger --choosedir=$HOME/.cache/ranger/rangerdir"
    CMD='ranger'
    WIN='ranger'
fi

# not in tmux session
if [[ ! "$TERM" =~ "screen" ]]; then
    SID=12
    if [ -z "$DISPLAY" ]; then
        CMD='vifm'
    else
        CMD='ranger'
    fi
fi

[[ $(tmux ls | egrep "^13:.*attached") ]] && SID=13

while getopts "bB" opt; do
    case $opt in
        b)
            WID=0

            if [ -z "$DISPLAY" ]; then
                #CMD='cd $(< $HOME/.cache/ranger/rangerdir); ranger --choosedir=$HOME/.cache/ranger/rangerdir'
                CMD='ranger'
                WIN='ranger'
            else
                CMD='vifmrun'
                WIN='vifmrun'
            fi
            ;;

        B)
            WID=15
            #WIN='yazi'
            #CMD='yazi ~/temp /opt/.porn 2>/dev/null'
            WIN='clifm'
            CMD='clifm --trash-dir=/var/tmp/Trash'
            ;;

        ?)  echo 'Usage: fmopen [-bB]'
            exit 1;;
    esac
done

shift $((OPTIND-1))

if [ $# -ne 0 ]; then
    echo 'Usage1: fmopen [-b]'
    exit 1
fi

tmux has-session -t $SID 2>/dev/null
if [ $? -ne 0 ]; then
    $CMD
    exit 0
fi

tmux select-window -t $SID:$WIN > /dev/null 2>&1
if [ $? -ne 0 ]; then
    tmux new-window -n $WIN -t $SID:$WID "stty -ixon; $CMD"
fi

exit 0
