#! /bin/bash

SESSION=0

if [ ! -z "$DISPLAY" ]; then
    vifm
    exit 0
fi

tmux has-session -t $SESSION
if [ $? -ne 0 ]; then
    vifm
    exit 0
fi

tmux select-window -t vifm > /dev/null 2>&1
if [ $? -ne 0 ]; then
    #tmux new-window -n vifm -t $SESSION:9 'DISPLAY=:0.0 vifm'
    tmux new-window -n vifm -t $SESSION:9 'vifm'
    tmux select-window -t vifm
fi

exit 0
