#! /usr/bin/env bash

if [ -z "$DISPLAY" ]; then
    SID=0
else
    SID=1
fi

WID=9
WIN='vifm'
CMD='vifm'

while getopts "e" opt; do
    case $opt in
        e) 
           CMD='ranger'
           WIN='ranger'
           WID=0
           ;;
        ?) echo 'Usage0: fmux [-e]'
           exit 1;;
    esac
done

shift $((OPTIND-1))  #This tells getopts to move on to the next argument.

if [ $# -ne 0 ]; then
    echo 'Usage1: fmux [-e]'
    exit 1
fi

tmux has-session -t $SID
if [ $? -ne 0 ]; then
    $CMD
    exit 0
fi

tmux select-window -t $SID:$WIN > /dev/null 2>&1
if [ $? -ne 0 ]; then
    tmux new-window -n $WIN -t $SID:$WID "$CMD"
fi

exit 0
