#! /bin/bash

SESSION=0

CMD='vifm'
WID='vifm'
SID=9

while getopts "e" opt; do
    case $opt in
        e) 
           CMD='ranger --confdir=~/.ranger'
           WID='ranger'
           SID=0
           ;;
        ?) echo 'Usage0: fmux [-e]'
           exit 1;;
    esac
done

shift $((OPTIND-1))  #This tells getopts to move on to the next argument.

if [ $# -ne 0 ]; then
    echo 'Usage1: fmux [-e]'
    exit 1
fi

if [ ! -z "$DISPLAY" ]; then
    $CMD
    exit 0
fi

tmux has-session -t $SESSION
if [ $? -ne 0 ]; then
    $CMD
    exit 0
fi

tmux select-window -t $WID > /dev/null 2>&1
if [ $? -ne 0 ]; then
    #tmux new-window -n vifm -t $SESSION:9 'DISPLAY=:0.0 vifm'
    tmux new-window -n $WID -t $SESSION:$SID "$CMD"
fi

exit 0
