#! /bin/bash

SESSION=0
arg=$1
strfile=${arg// /\\\ }
cwd=$PWD
strcwd=${cwd// /\\\ }

if [ -z $strfile ]; then
    echo "No file designated!"
    exit 1
fi

tmux has-session -t $SESSION
if [ $? -ne 0 ]; then
    vim $strfile
    exit 0
fi

tmux select-window -t vim
if [ $? -ne 0 ]; then
    tmux new-window -n vim -t $SESSION:7 'vim'
    tmux select-window -t vim
fi

tmux send-keys escape
tmux set-buffer ":cd $strcwd"
tmux paste-buffer
tmux send-keys C-m

tmux set-buffer ":e $strfile"
tmux paste-buffer
tmux send-keys C-m

exit 0
