#! /bin/bash

SESSION=0
file=$1
file=${file// /\\\ }

# fmvimux src/vim.c '+call cursor(116,16)'
cmd=$2
if [ "${cmd:0:1}" = '+' ]; then
    cmd=${cmd/#\+/}
    #echo "OKKK"
else
    cmd=""
    #echo "NOOO"
fi

cwd=$PWD
cwd=${cwd// /\\\ }

if [ -z $file ]; then
    echo "No file designated!"
    exit 1
fi

tmux has-session -t $SESSION
if [ $? -ne 0 ]; then
    vim $file
    exit 0
fi

tmux select-window -t vim > /dev/null 2>&1
if [ $? -ne 0 ]; then
    tmux new-window -n vim -t $SESSION:7 'vim'
    tmux select-window -t vim
fi

tmux send-keys escape
tmux set-buffer ":cd $cwd"
tmux paste-buffer
tmux send-keys C-m

tmux set-buffer ":e $file"
tmux paste-buffer
tmux send-keys C-m

if [ -z "$cmd" ]; then
    exit 0
fi

tmux set-buffer ":$cmd"
tmux paste-buffer
tmux send-keys C-m

exit 0
