#! /bin/bash

SESSION=0
temp="file://$PWD/$1"
abspath=${temp// /\\\ }

tmux has-session -t $SESSION
if [ $? -ne 0 ]; then
    if [ -z $1 ]; then
        TERM=jfbterm w3m .
    else
        TERM=jfbterm w3m $1
    fi

    exit 0
fi

tmux select-window -t w3m
if [ $? -ne 0 ]; then
    tmux new-window -c ~ -n w3m -t $SESSION:8 "TERM=jfbterm w3m $abspath"
    tmux select-window -t w3m
else
    tmux set-buffer "T $abspath"
    tmux paste-buffer
    tmux send-keys C-m
fi

exit 0
