#!/bin/bash

if [ -z "$DISPLAY" ]; then
    SID=0
else
    SID=1
fi

if [[ ! "$TERM" =~ "screen" ]]; then
    SID=13
fi

WID=12
WIN="fzfmux"

CMD="$*"' --height=0 --bind "enter:execute#fileopen {}#"'

tmux has-session -t $SID 2>/dev/null
if [ $? -ne 0 ]; then
    send-keys "$CMD"
    exit 0
fi

tmux select-window -t $SID:$WIN > /dev/null 2>&1
if [ $? -ne 0 ]; then
    tmux new-window -n $WIN -t $SID:$WID -c $HOME/temp
fi

tmux send-keys C-g  #quit pending fzf
tmux send-keys C-u  #clear existing input
tmux send-keys "$CMD" 'Enter'
exit 0
