#!/bin/bash

[[ -z "$DISPLAY" ]] && SID=0 || SID=1
[[ ! "$TERM" =~ "screen" ]] && SID=13    #not in tmux session
WID=12
WIN="fzfmux"

CMD="$*"' --height=0 --bind "enter:execute#fileopen {}#" --bind "esc:execute#tmux killw#"'

tmux has-session -t $SID 2>/dev/null
if [ $? -ne 0 ]; then
    "$CMD"
    exit 0
fi

tmux select-window -t $SID:$WIN > /dev/null 2>&1
if [ $? -ne 0 ]; then
    tmux new-window -n $WIN -t $SID:$WID -c $HOME/temp
fi

tmux send-keys -t $SID:$WID C-q  #quit pending fzf
tmux send-keys -t $SID:$WID C-u  #clear existing input
tmux send-keys -t $SID:$WID "$CMD" C-m
exit 0
