#!/bin/bash -x

PROJ_DIR=/home/lynna/.vim/bundle

##排除以下情况：
##1.非目录
##2.非git目录

function is_git_dir(){
    ret=`find $PWD -name ".git"`
    if [ -z "$ret" ];then
        return 1 #1为假
    else
        return 0 #0为真
    fi
}

function update_all()
{
    for d in `ls -A`
    do
        if [ -d "$PROJ_DIR/$d" ];then
            #echo $d;
            cd $PROJ_DIR/$d

            if is_git_dir $PWD;then
                echo "update directory: $PWD"
                `git pull`  2>&1 &
                sleep 5
                echo "update successfully"
            else
                echo "$PWD is not a git dir!"
            fi
        else
            echo "$d is not a dirctory"
        fi
    done
}

function update()
{
    `git pull` 2>&1 &
}


cd $PROJ_DIR

if [ -z  "$1"  ];then
    update_all
elif [ -d  "$PROJ_DIR/$1" ];then
    cd $PROJ_DIR/$1
    echo $PWD
    if is_git_dir $PWD;then
          update
    else
        echo "$PWD is not a git dir!"
    fi
else
    echo "not exist \"$PROJ_DIR/$1\""
    exit 0;
fi
