#!/bin/bash

if [ ! -f "$1" ]; then
    echo $1
    echo 'is not a file!'
    exit 1
fi

filename=$(basename -- "$1")
fileext="${filename##*.}"
filebase="${filename%.*}"
#echo $filename

shopt -s nocasematch
if [[ "$fileext" != "html" ]]; then
    echo $1, $fileext
    echo "Not ***.html file!"
    exit 2
fi

filepath=$(realpath -- "$1")
dirname=$(dirname -- "$filepath")
#echo $dirname
cd -- "$dirname"

ebook-convert "$filename" "$filebase".epub \
        --no-default-epub-cover \
        --line-height=6 \
        --page-breaks-before=/ --chapter=/  >/dev/null

#       --enable-heuristics \
#       --dont-split-on-page-breaks \


#~% FILE="example.tar.gz"
#~% echo "${FILE%%.*}"
#   example
#~% echo "${FILE%.*}"
#   example.tar
#~% echo "${FILE#*.}"
#   tar.gz
#~% echo "${FILE##*.}"
#   gz
