#!/bin/bash

[ $# -ne 1 ] && echo 'Only one arg!' && exit 1

appid=1
while getopts "12" opt; do
    case $opt in
        1)
            appid=1 ;;
        2)
            appid=2 ;;
        ?)
            echo 'Usage: html2txt [-12] <html_file>'
            exit 1;;
    esac
done
shift $((OPTIND-1))  #This tells getopts to move on to the next argument.

if [ ! -f "$1" ]; then
    echo "<$1> is not a file!"
    exit 2
fi

filename=$(basename -- "$1")
fileext="${filename##*.}"
filebase="${filename%.*}"
#echo $filename

shopt -s nocasematch
if [[ "$fileext" != "html" ]]; then
    echo "<$1> is not an HTML file!"
    exit 3
fi

filepath=$(realpath -- "$1")
dirname=$(dirname -- "$filepath")
#echo $dirname
cd -- "$dirname"

if [ $appid = "1" ]; then
    html2text --ignore-links --ignore-images --ignore-emphasis "$filename" > "$filebase".txt
    exit 0
fi

ebook-convert "$filename" "$filebase".txt > /dev/null
