#!/bin/bash

if [ ! -f "$1" ]; then
    echo $1
    echo 'is not a file!'
    exit 1
fi

filename=$(basename -- "$1")
fileext="${filename##*.}"
filebase="${filename%.*}"
#echo $filename

shopt -s nocasematch
if [[ "$fileext" != "html" ]]; then
    echo $1, $fileext
    echo "Not ***.html file!"
    exit 2
fi

filepath=$(realpath -- "$1")
dirname=$(dirname -- "$filepath")
#echo $dirname
cd -- "$dirname"

ebook-convert "$filename" "$filebase".txt
