#! /bin/bash

shopt -s nullglob
shopt -s globstar
shopt -s nocaseglob

ALT="0"
recursive="FALSE"
slideshow="FALSE"

[[ -z "$DISPLAY" ]] && SID=0 || SID=1
[[ -z "$TMUX" ]] && SID=12  #not in tmux session
[[ $(tmux ls | egrep "13:.*attached") ]] && SID=13
[[ "$(tmux display-message -p -F '#{session_name}')" == "nova" ]] && SID="nova"
WID=11
WIN="imgview"
CMD=""
PROG=""

#If an option should be followed by an argument, it should be followed by a ":".
#The leading ":" suppresses error messages from getopts.
#while getopts ":brsd:" opt; do
while getopts "bBrsd:" opt; do
    case $opt in
        b) ALT="1";;
        B) ALT="2";;
        r) recursive="TRUE";;
        s) slideshow="TRUE";;
        d) 
           if [ -d "$OPTARG" ]; then
               cd "$OPTARG"
           else
               echo 'option -d must be followed by a directory!'
               exit 1
           fi
           ;;
        ?) echo 'Usage: imgview [-b] [-r] [-s] [-d dir] <file>'
           exit 1;;
    esac
done

shift $((OPTIND -1))  #This tells getopts to move on to the next argument.

file="$1"
if [ ! -z "$file" -a ! -f "$file" ]; then
    echo "$0:$file is not a file!"
    exit 1
fi

# console
if [ -z "$DISPLAY" ]; then
    #PROG="fim"
    PROG="mpv --vo=drm --config-dir=/opt/conf/mpi"
    if [ "$ALT" = "1" ]; then
        PROG="fbv"
    elif [ "$ALT" = "2" ]; then
        PROG="jfbview"
    fi

    if [ "$slideshow" = "TRUE" ]; then
        if [ "$ALT" = "0" ]; then
            if [[ $PROG =~ "fim" ]]; then
                PROG+=" -c \"endless_slideshow\""
            fi
        elif [ "$ALT" = "1" ]; then
            PROG+=" -s 10"
        fi
    fi
# xwindow
else
    #PROG="feh -ZF"
    PROG="feh -F -S filename"
    if [ "$ALT" = "1" ]; then
        PROG="sxiv -f"
        #PROG="sxiv -ft"
    elif [ "$ALT" = "2" ]; then
        PROG="feh -F -S mtime"
        #PROG="pqiv -f"
        #PROG='pqiv -f --action="montage_mode_enter()" --thumbnail-size=128x128'
        #PROG="pho -p"
        #PROG='vimiv'
        #PROG="imv -f"
    fi

    if [ "$slideshow" = "TRUE" ]; then
        #PROG="feh -S filename -ZF -D 1"
        PROG="feh -S filename -F -D 1"
        if [ "$ALT" = "1" ]; then
            PROG="pqiv -fs"
        elif [ "$ALT" = "2" ]; then
            PROG="pho -p -s1"
            #PROG="sxiv -fS 1"
            #PROG="vimiv --slideshow"
            #PROG="imv -f -t 1"
        fi
    fi
fi

# jfbview can only input one file to view
if [[ $PROG =~ "jfbview" ]]; then
    CMD="$PROG $file"
    setterm -cursor off; $CMD
    exit 0
fi

FILES="$file"
if [ "$recursive" = "FALSE" ]; then
    FILES+=" *.{jpg,jpeg,png,bmp,gif,ppm,xpm,webp}"
else
    FILES+=" {,**/}*.{jpg,jpeg,png,bmp,gif,ppm,xpm,webp}"
fi
#echo $FILES > ~/dddd

CMD="$PROG $FILES" > /dev/null 2>&1

tmux has-session -t $SID 2>/dev/null
if [ $? -ne 0 ]; then
    $PROG "$file" *.{jpg,jpeg,png,bmp,gif,ppm,xpm,webp}
    exit 0
fi

tmux select-window -t $SID:$WIN > /dev/null 2>&1
if [ $? -ne 0 ]; then
    tmux new-window -n $WIN -t $SID:$WID "setterm -cursor off; $CMD 2>/dev/null"
    #CURR_SID="$(tmux display-message -p -F '#{session_name}')"
    #if [[ $CURR_SID == "nova" && $DISPLAY == "" ]]; then
    #    tmux detach-client
    #fi
fi

exit 0

## https://github.com/ranger/ranger/blob/master/examples/rifle_sxiv.sh
## https://q2a.vifm.info/431/sxiv-scroll-through-all-images
if [[ ! -f $1 ]]; then
    echo "$0: first argument is not a file!" >&2
    exit 1
fi

file=$(basename -- "$1")
dir=$(dirname -- "$1")
arr=()
shift

cd -- "$dir"

for i in *; do
    [[ -f "$i" ]] || continue
    arr+=("$i")
    [[ "$i" == "$file" ]] && n=${#arr[@]}
done

exec sxiv -n "$n" "$@" "${arr[@]}"
