#! /bin/bash

shopt -s nullglob
shopt -s globstar
shopt -s nocaseglob

ALT="0"
recursive="FALSE"
slideshow="FALSE"

[[ -z "$DISPLAY" ]] && SID=0 || SID=1
[[ ! "$TERM" =~ "screen" ]] && SID=13    #not in tmux session
WID=11
WIN="imgview"
CMD=""
PROG=""

#If an option should be followed by an argument, it should be followed by a ":".
#The leading ":" suppresses error messages from getopts.
#while getopts ":brsd:" opt; do
while getopts "bBrsd:" opt; do
    case $opt in
        b) ALT="1";;
        B) ALT="2";;
        r) recursive="TRUE";;
        s) slideshow="TRUE";;
        d) 
           if [ -d "$OPTARG" ]; then
               cd "$OPTARG"
           else
               echo 'option -d must be followed by a directory!'
               exit 1
           fi
           ;;
        ?) echo 'Usage: imgview [-b] [-r] [-s] [-d dir] <file>'
           exit 1;;
    esac
done

shift $((OPTIND -1))  #This tells getopts to move on to the next argument.

file="$1"
if [ ! -z "$file" -a ! -f "$file" ]; then
    echo "$0:$file is not a file!"
    exit 1
fi

# console
if [ -z "$DISPLAY" ]; then
    PROG="fim"
    if [ "$ALT" = "1" ]; then
        PROG="fbv"
    elif [ "$ALT" = "2" ]; then
        PROG="jfbview"
    fi

    if [ "$slideshow" = "TRUE" ]; then
        if [ "$ALT" = "0" ]; then
            PROG+=" -c \"endless_slideshow\""
        elif [ "$ALT" = "1" ]; then
            PROG+=" -s 10"
        fi
    fi
# xwindow
else
    PROG="pho -p"
    if [ "$ALT" = "1" ]; then
        PROG="sxiv -ft"
    elif [ "$ALT" = "2" ]; then
        #PROG='pqiv -f --action="montage_mode_enter()" --thumbnail-size=128x128'
        PROG='vimiv'
        #PROG="feh -F"
        #PROG="imv -f"
    fi

    if [ "$slideshow" = "TRUE" ]; then
        if [ "$ALT" = "0" ]; then
            PROG="pho -p -s1"
        elif [ "$ALT" = "1" ]; then
            PROG="feh -F -D 1"
        elif [ "$ALT" = "2" ]; then
            PROG="pqiv -fs"
            #PROG="sxiv -fS 1"
            #PROG="vimiv --slideshow"
            #PROG="imv -f -t 1"
        fi
    fi
fi

# jfbview can only input one file to view
if [[ $PROG =~ "jfbview" ]]; then
    CMD="$PROG $file"
    setterm -cursor off; $CMD
    exit 0
fi

FILES="$file"
if [ "$recursive" = "FALSE" ]; then
    FILES+=" *.{jpg,jpeg,png,bmp,gif,ppm,xpm}"
else
    FILES+=" {,**/}*.{jpg,jpeg,png,bmp,gif,ppm,xpm}"
fi
#echo $FILES > ~/dddd

CMD="$PROG $FILES" > /dev/null 2>&1

tmux has-session -t $SID 2>/dev/null
if [ $? -ne 0 ]; then
    $PROG "$file" *.{jpg,jpeg,png,bmp,gif,ppm,xpm}
    exit 0
fi

tmux select-window -t $SID:$WIN > /dev/null 2>&1
if [ $? -ne 0 ]; then
    tmux new-window -n $WIN -t $SID:$WID "setterm -cursor off; $CMD 2>/dev/null"
fi

exit 0
