#! /bin/bash

shopt -s nullglob
shopt -s globstar
shopt -s nocaseglob

recursive="FALSE"
slideshow="FALSE"

#If an option should be followed by an argument, it should be followed by a ":".
#The leading ":" suppresses error messages from getopts.
#while getopts ":rsd:" opt; do
while getopts "rsd:" opt; do
    case $opt in
        r) recursive="TRUE";;
        s) slideshow="TRUE";;
        d) 
           if [ -d "$OPTARG" ]; then
               cd "$OPTARG"
           else
               echo 'option -d must followed by directory'
               exit 1
           fi
           ;;
        ?) echo 'Usage: imgview [-r] [-s] [-d dir] [file]'
           exit 1;;
    esac
done

shift $((OPTIND-1))  #This tells getopts to move on to the next argument.

if [ $# -gt 1 ]; then
    echo "Only one file supported!"
    exit 1
fi

file=$1
if [ ! -z "$file" -a ! -f "$file" ]; then
    echo "$file is not a file!"
    exit 1
fi

#while [ $# -ne 0 ]; do
#    file=$1
#    file=${file// /\\\ }
#    file=${file##*/}  
#    #file=`basename "$file"`  #This is another way to get the base file name.
#    #file_BASE=`echo "${file%.*}"`  #file without extension
#    #file_EXT="${file##*.}"  #file extension
#
#    echo "$file"
#    shift  #Move on to next input file.
#done
#exit 0

if [ -z "$DISPLAY" ]; then
    if [ "$recursive" = "FALSE" ]; then
        if [ "$slideshow" = "FALSE" ]; then
            fim "$file" *.{jpg,jpeg,png,bmp,gif,ppm,xpm} > /dev/null 2>&1
        else
            fim -c 'endless_slideshow' *.{jpg,jpeg,png,bmp,gif,ppm,xpm} > /dev/null 2>&1
        fi
    else
        if test "$slideshow" = "FALSE"; then
            fim "$file" {,**/}*.{jpg,jpeg,png,bmp,gif,ppm,xpm} > /dev/null 2>&1
        else
            fim -c 'endless_slideshow' {,**/}*.{jpg,jpeg,png,bmp,gif,ppm,xpm} > /dev/null 2>&1
        fi
    fi
else
    if [ "$recursive" = "FALSE" ]; then
        if [ "$slideshow" = "FALSE" ]; then
            pho -p "$file" *.{jpg,jpeg,png,bmp,gif,ppm,xpm} > /dev/null 2>&1 &
        else
            pho -p -s1 *.{jpg,jpeg,png,bmp,gif,ppm,xpm} > /dev/null 2>&1 &
        fi
    else
        if test "$slideshow" = "FALSE"; then
            pho -p "$file" **/*.{jpg,jpeg,png,bmp,gif,ppm,xpm} > /dev/null 2>&1 &
        else
            pho -p -s1 **/*.{jpg,jpeg,png,bmp,gif,ppm,xpm} > /dev/null 2>&1 &
        fi
    fi
fi

exit 0
