#!/bin/bash

# https://github.com/akavel/up
# up is the Ultimate Plumber, a tool for writing Linux pipes
# in a terminal-based UI interactively with instant live preview

# |& connects standard output&error of the first command to the second one
# |   only connects standard output of the first command to the second one

$* |& up
