#!/bin/bash

SESSION=0

if [ ! -z "$DISPLAY" ]; then
    elinks
    exit 0
fi

tmux has-session -t $SESSION
if [ $? -ne 0 ]; then
    elinks
    exit 0
fi

tmux select-window -t lynx > /dev/null 2>&1
if [ $? -ne 0 ]; then
    tmux new-window -n lynx -t $SESSION:5 'elinks'
fi

exit 0
