#! /bin/bash

if [ -z "$DISPLAY" ]; then
    SID=0
else
    SID=1
fi

WID=4
WIN="mailmgr"
CMD="mutt"

tmux has-session -t $SID
if [ $? -ne 0 ]; then
    $CMD
    exit 0
fi

tmux select-window -t $SID:$WIN > /dev/null 2>&1
if [ $? -ne 0 ]; then
    tmux new-window -n $WIN -t $SID:$WID "stty -ixon; $CMD"
fi

exit 0
