#! /bin/bash

[[ -z "$DISPLAY" ]] && SID=0 || SID=1
[[ -z "$TMUX" ]] && SID=12  #not in tmux session
[[ $(tmux ls | egrep "^13:.*attached") ]] && SID=13
WID=4
WIN="mail"
CMD="mutt"

tmux has-session -t $SID 2>/dev/null
if [ $? -ne 0 ]; then
    $CMD
    exit 0
fi

tmux select-window -t $SID:$WIN > /dev/null 2>&1
if [ $? -ne 0 ]; then
    tmux new-window -n $WIN -t $SID:$WID "stty -ixon; $CMD"
fi

exit 0
