#! /bin/bash

SID=0
WID=4
WIN="mailmgr"
CMD="mutt"

# not in tmux session
if [[ ! "$TERM" =~ "screen" ]]; then
    SID=13
fi

tmux has-session -t $SID 2>/dev/null
if [ $? -ne 0 ]; then
    $CMD
    exit 0
fi

tmux select-window -t $SID:$WIN > /dev/null 2>&1
if [ $? -ne 0 ]; then
    tmux new-window -n $WIN -t $SID:$WID "stty -ixon; $CMD"
fi

exit 0
