#! /bin/bash

if [ -z "$DISPLAY" ]; then
    SID=0
else
    SID=1
fi

WID=7
WIN="vim"
CMD="vim"

tmux has-session -t $SID
if [ $? -ne 0 ]; then
    man $1
    exit 0
fi

tmux select-window -t $SID:$WIN > /dev/null 2>&1
if [ $? -ne 0 ]; then
    tmux new-window -n $WIN -t $SID:$WID "stty -ixon; $CMD"
    tmux select-window -t $SID:$WIN
fi

tmux send-keys -t $SID:$WID escape ":Man $1" C-m
tmux send-keys -t $SID:$WID so
exit 0
