#! /bin/bash

[[ -z "$DISPLAY" ]] && SID=0 || SID=1
[[ ! "$TERM" =~ "screen" ]] && SID=12    #not in tmux session
[[ $(tmux ls | egrep "13:.*attached") ]] && SID=13
[[ "$(tmux display-message -p -F '#{session_name}')" == "nova" ]] && SID="nova"
WID=7
WIN="vim"
CMD="vim"

tmux has-session -t $SID 2>/dev/null
if [ $? -ne 0 ]; then
    man $1
    exit 0
fi

tmux select-window -t $SID:$WIN > /dev/null 2>&1
if [ $? -ne 0 ]; then
    tmux new-window -n $WIN -t $SID:$WID "stty -ixon; $CMD"
    tmux select-window -t $SID:$WIN
fi

tmux send-keys -t $SID:$WID escape ":Man $1" C-m
tmux send-keys -t $SID:$WID so
exit 0
