#!/bin/bash

MIMETYPE=$(mimetype -b "$1")
case "$MIMETYPE" in
    audio/*)
        (exiftool "$1" |grep Bitrate |cut -d':' -f 2 |sed -e 's/[ \t]*//g' && exiftool "$1" |grep ^Duration |cut -d':' -f 2-4) |tr -d '\n'
        exit 0;;
    image/*)
        exiftool "$1" |grep 'Image Size' |cut -d':' -f 2 |sed -e 's/^[ \t]*//'
        #identify "$1" | cut -d' ' -f 3
        exit 0;;
    video/*)
        (exiftool "$1" |grep 'Image Size' |cut -d':' -f 2 |sed -e 's/^[ \t]*//' && exiftool "$1" |grep ^Duration |cut -d':' -f 2-4) |tr -d '\n'
        exit 0;;
    inode/directory | inode/mount-point)
        #df -h "$1" |egrep -iv 'Used' |sed 's/\s\+/ /g' |cut -d' ' -f 4
        df -h "$1" |sed '1d' |awk '{print $4,$2}'
esac

exit 1
