#!/bin/bash

tsls=0
while getopts "t" opt; do
    case $opt in
        t)
            tsls=1 ;;
        ?)
            echo 'Usage: medinfo [-t]'
            exit 1;;
    esac
done
shift $((OPTIND-1))  #This tells getopts to move on to the next argument.

[[ $tsls -eq 1 ]] && {
    tsp | grep running  | sed -e 's/mpg321/mpgXXX running  mpg321/' | awk -F"mpgXXX " '{print $2}'
    echo '--------'
    tsp | grep queued   | sed -e 's/mpg321/mpgXXX queued   mpg321/' | awk -F"mpgXXX " '{print $2}'
    echo '--------'
    tsp | grep finished | sed -e 's/mpg321/mpgXXX finished mpg321/' | awk -F"mpgXXX " '{print $2}'

    exit 0
}

MIMETYPE=$(mimetype -b -- "$1")
case "$MIMETYPE" in
    audio/*)
        (exiftool "$1" |grep Bitrate |cut -d':' -f 2 |sed -e 's/[ \t]*//g' && exiftool "$1" |grep ^Duration |cut -d':' -f 2-4) |tr -d '\n'
        exit 0;;
    image/*)
        exiftool "$1" |grep 'Image Size' |cut -d':' -f 2 |sed -e 's/^[ \t]*//'
        #identify "$1" | cut -d' ' -f 3
        exit 0;;
    video/*)
        (exiftool "$1" |grep 'Image Size' |cut -d':' -f 2 |sed -e 's/^[ \t]*//' && exiftool "$1" |grep ^Duration |cut -d':' -f 2-4) |tr -d '\n'
        exit 0;;
    inode/directory | inode/mount-point)
        #df -h "$1" |egrep -iv 'Used' |sed 's/\s\+/ /g' |cut -d' ' -f 4
        df -h "$1" |sed '1d' |awk '{print $4,$2}'
esac

echo "Unkown MIMETYPE = \"MIMETYPE\"!"
exit 1
