#!/bin/bash

iii=0
ump=0
txt=0
sds=0
sdu=0
sdv=0
sdw=0
sdx=0

while getopts "apstuvwxi" opt; do
    case $opt in
        i)
           iii=1
           ;;
        p)
           ump=1
           ;;
        s)
           sds=1
           ;;
        t)
           txt=1
           ;;
        u)
           sdu=1
           ;;
        v)
           sdv=1
           ;;
        w)
           sdw=1
           ;;
        x)
           sdx=1
           ;;
        a)
           sds=1
           txt=1
           sdu=1
           sdv=1
           sdw=1
           sdx=1
           ump=1
           ;;
        ?)
           echo 'mudisk -[apstuvwx]'
           exit 1;;
    esac
done

shift $((OPTIND-1))  #This tells getopts to move on to the next argument.

wcs=$(ls /media/simone/sandisk_s  2>/dev/null | wc -l)
wcu=$(ls /media/simone/sandisk_u  2>/dev/null | wc -l)
wcv=$(ls /media/simone/sandisk_v  2>/dev/null | wc -l)
wcw=$(ls /media/simone/sandisk_w  2>/dev/null | wc -l)
wcx=$(ls /media/simone/sandisk_x1 2>/dev/null | wc -l)
wct=$(ls /opt/.porn/text/000      2>/dev/null | wc -l)

if [ $iii -eq 1 ]; then
  if [ $sds -eq 1 ] && [ $wcs -eq 0 ]; then
    sudo mount -t exfat -o rw,nosuid,nodev,relatime,fmask=0133,dmask=0022,codepage=437,iocharset=utf8,showexec,uid=1000,gid=1000 /dev/disk/by-uuid/EA1D-0944 /media/simone/sandisk_s
  fi

  if [ $sdu -eq 1 ] && [ $wcu -eq 0 ]; then
    sudo mount -t vfat -o rw,nosuid,nodev,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=utf8,showexec,uid=1000,gid=1000 /dev/disk/by-uuid/3166-6338 /media/simone/sandisk_u
  fi

  if [ $sdv -eq 1 ] && [ $wcv -eq 0 ]; then
    sudo mount -o rw,nosuid,nodev,relatime,data=ordered,uhelper=udisks2 /dev/disk/by-uuid/d042e951-6889-412c-8b0d-c792593f7b20 /media/simone/sandisk_v
  fi

  if [ $sdw -eq 1 ] && [ $wcw -eq 0 ]; then
    sudo mount -o rw,nosuid,nodev,relatime,data=ordered /dev/disk/by-label/udisk_hama /media/simone/sandisk_w
  fi

  if [ $sdx -eq 1 ] && [ $wcx -eq 0 ]; then
    sudo mount -o rw,nosuid,nodev,relatime,stripe=32696,data=ordered,uhelper=udisks2 /dev/disk/by-label/sandisk_ext /media/simone/sandisk_x1

    sleep 1s
    sudo mount -o rw,nosuid,nodev,relatime,stripe=32696,data=ordered,uhelper=udisks2 /dev/disk/by-label/sandisk_exp /media/simone/sandisk_x2
  fi

  if [ $txt -eq 1 ] && [ $wct -eq 0 ]; then
    sudo mount -t ecryptfs /opt/.porn/text /opt/.porn/text -o ecryptfs_cipher=aes,ecryptfs_key_bytes=16,ecryptfs_passthrough=n,ecryptfs_enable_filename_crypto=y,ecryptfs_fnek_sig=85e5a0a7dcf6b743
  fi

  exit 0
fi

[ ! -f /opt/.priv/password ] && exit 1

password="$(< /opt/.priv/password)"
passphrase="$(< /opt/.priv/passphrase)"

/usr/bin/expect << EOD
  set timeout 3

  if {$sds == 1 && $wcs == 0} {
    sleep 0.5
    spawn sudo mount -t exfat -o rw,nosuid,nodev,relatime,fmask=0133,dmask=0022,codepage=437,iocharset=utf8,showexec,uid=1000,gid=1000 /dev/disk/by-uuid/EA1D-0944 /media/simone/sandisk_s
    expect "password"
    send "$password\r"
  }

  if {$sdu == 1 && $wcu == 0} {
    sleep 0.5
    spawn sudo mount -t vfat -o rw,nosuid,nodev,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=utf8,showexec,uid=1000,gid=1000 /dev/disk/by-uuid/3166-6338 /media/simone/sandisk_u
    expect "password"
    send "$password\r"
  }

  if {$sdv == 1 && $wcv == 0} {
    sleep 0.5
    spawn sudo mount -o rw,nosuid,nodev,relatime,data=ordered,uhelper=udisks2 /dev/disk/by-uuid/d042e951-6889-412c-8b0d-c792593f7b20 /media/simone/sandisk_v
    expect "password"
    send "$password\r"
  }

  if {$sdw == 1 && $wcw == 0} {
    sleep 0.5
    spawn sudo mount -o rw,nosuid,nodev,relatime,data=ordered /dev/disk/by-label/udisk_hama /media/simone/sandisk_w
    expect "password"
    send "$password\r"
  }

  if {$sdx == 1 && $wcx == 0} {
    sleep 0.5
    spawn sudo mount -o rw,nosuid,nodev,relatime,stripe=32696,data=ordered,uhelper=udisks2 /dev/disk/by-label/sandisk_ext /media/simone/sandisk_x1
    expect "password"
    send "$password\r"

    sleep 0.5
    spawn sudo mount -o rw,nosuid,nodev,relatime,stripe=32696,data=ordered,uhelper=udisks2 /dev/disk/by-label/sandisk_exp /media/simone/sandisk_x2
    expect "password"
    send "$password\r"
  }

  if {$txt == 1 && $wct == 0} {
    sleep 0.5
    spawn sudo mount -t ecryptfs /opt/.porn/text /opt/.porn/text -o ecryptfs_cipher=aes,ecryptfs_key_bytes=16,ecryptfs_passthrough=n,ecryptfs_enable_filename_crypto=y,ecryptfs_fnek_sig=85e5a0a7dcf6b743
    expect "password"
    send "$password\r"
    expect "Passphrase"
    send "$passphrase\r"
  }

  if {$ump == 1} {
    sleep 0.5
    spawn sudo umount /opt/.priv
    expect "password"
    send "$password\r"
  }

  expect eof
EOD
