#!/bin/bash

winC=0
winD=0
exp=0
pls=0
txt=0
sda=0
sds=0
sdu=0
sdv=0
sdw=0
sdx=0
mnt=1

while getopts "acdestuvwxlU" opt; do
    case $opt in
        c)
           winC=1 ;;
        d)
           winD=1 ;;
        e)
           exp=1 ;;
        l)
           pls=1 ;;
        s)
           sds=1 ;;
        t)
           txt=1 ;;
        u)
           sdu=1 ;;
        v)
           sdv=1 ;;
        w)
           sdw=1 ;;
        x)
           sdx=1 ;;
        U)
           mnt=0 ;;
        a)
           sda=1
           sds=1
           txt=1
           sdu=1
           sdv=1
           sdw=1
           sdx=1
           ;;
        ?)
           echo 'mudisk -[adestuvwxlU]'
           exit 1 ;;
    esac
done

shift $((OPTIND-1))  #This tells getopts to move on to the next argument.

#export /media/simone tree files
if [ $exp -eq 1 ] && [ $sda -eq 1 ]; then
    tree -f -L 2 /media/simone > /opt/misc/docs/files-sandisks
    echo "tree to files-sandisks!"
    exit 0
fi

wcc=$(ls /media/simone/winC       2>/dev/null | wc -l)
wcd=$(ls /media/simone/winD       2>/dev/null | wc -l)
wcs=$(ls /media/simone/sandisk_s  2>/dev/null | wc -l)
wcu=$(ls /media/simone/sandisk_u  2>/dev/null | wc -l)
wcv=$(ls /media/simone/sandisk_v  2>/dev/null | wc -l)
wcw=$(ls /media/simone/sandisk_w  2>/dev/null | wc -l)
wcx=$(ls /media/simone/sandisk_x1 2>/dev/null | wc -l)
wct=$(ls /opt/.porn/text/000      2>/dev/null | wc -l)

#list which process is occupying the mount point
if [ $pls -eq 1 ]; then
    [[ $txt == 1 ]] && [[ $wct != 0 ]] && echo ttt-lsof && lsof /opt/.porn/text
    [[ $sds == 1 ]] && [[ $wcs != 0 ]] && echo sss-lsof && lsof /media/simone/sandisk_s
    [[ $sdu == 1 ]] && [[ $wcu != 0 ]] && echo uuu-lsof && lsof /media/simone/sandisk_u
    [[ $sdv == 1 ]] && [[ $wcv != 0 ]] && echo vvv-lsof && lsof /media/simone/sandisk_v
    [[ $sdw == 1 ]] && [[ $wcw != 0 ]] && echo www-lsof && lsof /media/simone/sandisk_w
    [[ $sdx == 1 ]] && [[ $wcx != 0 ]] && echo xxx-lsof && {
        lsof /media/simone/sandisk_x1
        lsof /media/simone/sandisk_x2
    }

    exit 0
fi

#umount the specific mount point
if [ $mnt -eq 0 ]; then
  [[ $winC == 1 ]] && [[ $wcc != 0 ]] && echo ccc-umnt && sudo umount /media/simone/winC
  [[ $winD == 1 ]] && [[ $wcd != 0 ]] && echo ddd-umnt && sudo umount /media/simone/winD
  [[ $txt == 1 ]] && [[ $wct != 0 ]] && echo ttt-umnt && sudo umount /opt/.porn/text
  [[ $sds == 1 ]] && [[ $wcs != 0 ]] && echo sss-umnt && sudo umount /media/simone/sandisk_s
  [[ $sdu == 1 ]] && [[ $wcu != 0 ]] && echo uuu-umnt && sudo umount /media/simone/sandisk_u
  [[ $sdv == 1 ]] && [[ $wcv != 0 ]] && echo vvv-umnt && sudo umount /media/simone/sandisk_v
  [[ $sdw == 1 ]] && [[ $wcw != 0 ]] && echo www-umnt && sudo umount /media/simone/sandisk_w
  [[ $sdx == 1 ]] && [[ $wcx != 0 ]] && echo xxx-umnt && {
      sudo umount /media/simone/sandisk_x1
      sudo umount /media/simone/sandisk_x2
  }

  exit 0
fi

#mount the specific point when the .priv is not available
wcp=$(ls /opt/.priv/priv 2>/dev/null | wc -l)
if [ $wcp -eq 0 ]; then
  #mount winC manually
  if [[ $winC -eq 1 ]] && [[ $wcc -eq 0 ]]; then
    echo +winC+
    sudo mount -o rw,nosuid,nodev,relatime,fmask=0022,dmask=0022,uid=1000,gid=1000 /dev/nvme0n1p3 /media/simone/winC
  fi
  
  #mount winD manually
  if [[ $winD -eq 1 ]] && [[ $wcd -eq 0 ]]; then
    echo +winD+
    sudo mount -o rw,nosuid,nodev,relatime,fmask=0022,dmask=0022,uid=1000,gid=1000 /dev/nvme0n1p4 /media/simone/winD
  fi
  
  #mount text manually
  if [ $txt -eq 1 ] && [ $wct -eq 0 ]; then
    echo +ttt+
    sudo mount -t ecryptfs /opt/.porn/text /opt/.porn/text -o ecryptfs_cipher=aes,ecryptfs_key_bytes=16,ecryptfs_passthrough=n,ecryptfs_enable_filename_crypto=y,ecryptfs_fnek_sig=85e5a0a7dcf6b743
  fi
  
  #mount sandisk_s manually
  if [ $sds -eq 1 ] && [ $wcs -eq 0 ] && [ -e /dev/disk/by-uuid/EA1D-0944 ]; then
    echo +sss+
    sudo mount -t exfat -o rw,nosuid,nodev,relatime,fmask=0133,dmask=0022,codepage=437,iocharset=utf8,showexec,uid=1000,gid=1000 /dev/disk/by-uuid/EA1D-0944 /media/simone/sandisk_s
  fi
  
  #mount sandisk_u manually
  if [ $sdu -eq 1 ] && [ $wcu -eq 0 ] && [ -e /dev/disk/by-uuid/3166-6338 ]; then
    echo +uuu+
    sudo mount -t vfat -o rw,nosuid,nodev,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=utf8,showexec,uid=1000,gid=1000 /dev/disk/by-uuid/3166-6338 /media/simone/sandisk_u
  fi
  
  #mount sandisk_v manually
  if [ $sdv -eq 1 ] && [ $wcv -eq 0 ] && [ -e /dev/disk/by-uuid/d042e951-6889-412c-8b0d-c792593f7b20 ]; then
    echo +vvv+
    sudo mount -o rw,nosuid,nodev,relatime,data=ordered,uhelper=udisks2 /dev/disk/by-uuid/d042e951-6889-412c-8b0d-c792593f7b20 /media/simone/sandisk_v
  fi
  
  #mount sandisk_w manually
  if [ $sdw -eq 1 ] && [ $wcw -eq 0 ] && [ -e /dev/disk/by-uuid/3534-6562 ]; then
  #if [ $sdw -eq 1 ] && [ $wcw -eq 0 ] && [ -e /dev/disk/by-label/udisk_hama ]; then
    echo +www+
    sudo mount -o rw,nosuid,nodev,relatime,stripe=32696,data=ordered,uhelper=udisks2 /dev/disk/by-uuid/3534-6562 /media/simone/sandisk_w
    #sudo mount -o rw,nosuid,nodev,relatime,stripe=32696,data=ordered,uhelper=udisks2 /dev/disk/by-label/udisk_hama /media/simone/sandisk_w
  fi
  
  #mount sandisk_x manually
  if [ $sdx -eq 1 ] && [ $wcx -eq 0 ] && [ -e /dev/disk/by-label/sandisk_ext ]; then
    echo +xxx1+
    sudo mount -o rw,nosuid,nodev,relatime,stripe=32696,data=ordered,uhelper=udisks2 /dev/disk/by-label/sandisk_ext /media/simone/sandisk_x1
  
    sleep 1s
    echo +xxx2+
    sudo mount -o rw,nosuid,nodev,relatime,stripe=32696,data=ordered,uhelper=udisks2 /dev/disk/by-label/sandisk_exp /media/simone/sandisk_x2
  fi

  exit 0
fi

#mount the specific point when the .priv is available
[ ! -f /opt/.priv/password ]   && exit 1 || password="$(< /opt/.priv/password)"
[ ! -f /opt/.priv/passphrase ] && exit 1 || passphrase="$(< /opt/.priv/passphrase)"

exist_sdw_src=0; [ -e /dev/disk/by-label/udisk_hama ] && exist_sdw_src=1
exist_sds_src=0; [ -e /dev/disk/by-uuid/EA1D-0944 ]   && exist_sds_src=1

/usr/bin/expect << EOD
  set timeout 3

  if {$mnt == 0} {
    if {$winC == 1 && $wcc != 0} {
      puts "-winC-"
      sleep 0.5
      spawn sudo umount /media/simone/winC
      expect "password"
      send "$password\r"
    }

    if {$winD == 1 && $wcd != 0} {
      puts "-winD-"
      sleep 0.5
      spawn sudo umount /media/simone/winD
      expect "password"
      send "$password\r"
    }

    if {$txt == 1 && $wct != 0} {
      puts "-ttt-"
      sleep 0.5
      spawn sudo umount /opt/.porn/text
      expect "password"
      send "$password\r"
    }

    if {$sds == 1 && $wcs != 0 && $exist_sds_src == 1} {
      puts "\n\n-sss-"
      sleep 0.5
      spawn sudo umount /media/simone/sandisk_s
      expect "password"
      send "$password\r"
    }

    if {$sdu == 1 && $wcu != 0} {
      puts "\n\n-uuu-"
      sleep 0.5
      spawn sudo umount /media/simone/sandisk_u
      expect "password"
      send "$password\r"
    }

    if {$sdv == 1 && $wcv != 0} {
      puts "\n\n-vvv-"
      sleep 0.5
      spawn sudo umount /media/simone/sandisk_v
      expect "password"
      send "$password\r"
    }

    if {$sdw == 1 && $wcw != 0 && $exist_sdw_src == 1} {
      puts "\n\n-www-"
      sleep 0.5
      spawn sudo umount /media/simone/sandisk_w
      expect "password"
      send "$password\r"
    }

    if {$sdx == 1 && $wcx != 0} {
      puts "\n\n-xxx1-"
      sleep 0.5
      spawn sudo umount /media/simone/sandisk_x1
      expect "password"
      send "$password\r"

      puts "\n\n-xxx2-"
      sleep 0.5
      spawn sudo umount /media/simone/sandisk_x2
      expect "password"
      send "$password\r"
    }

    expect eof
    exit
  }

  if {$winC == 1 && $wcd == 0} {
    puts "+winC+"
    sleep 0.5
    spawn sudo mount -o rw,nosuid,nodev,relatime,fmask=0022,dmask=0022,uid=1000,gid=1000 /dev/nvme0n1p3 /media/simone/winC
    expect "password"
    send "$password\r"
  }

  if {$winD == 1 && $wcd == 0} {
    puts "+winD+"
    sleep 0.5
    spawn sudo mount -o rw,nosuid,nodev,relatime,fmask=0022,dmask=0022,uid=1000,gid=1000 /dev/nvme0n1p4 /media/simone/winD
    expect "password"
    send "$password\r"
  }

  if {$txt == 1 && $wct == 0} {
    puts "+ttt+"
    sleep 0.5
    spawn sudo mount -t ecryptfs /opt/.porn/text /opt/.porn/text -o ecryptfs_cipher=aes,ecryptfs_key_bytes=16,ecryptfs_passthrough=n,ecryptfs_enable_filename_crypto=y,ecryptfs_fnek_sig=85e5a0a7dcf6b743
    expect "password"
    send "$password\r"
    expect "Passphrase"
    send "$passphrase\r"
  }

  if {$sds == 1 && $wcs == 0 && $exist_sds_src == 1} {
    puts "\n\n+sss+"
    sleep 0.5
    spawn sudo mount -t exfat -o rw,nosuid,nodev,relatime,fmask=0133,dmask=0022,codepage=437,iocharset=utf8,showexec,uid=1000,gid=1000 /dev/disk/by-uuid/EA1D-0944 /media/simone/sandisk_s
    expect "password"
    send "$password\r"
  }

  if {$sdu == 1 && $wcu == 0} {
    puts "\n\n+uuu+"
    sleep 0.5
    spawn sudo mount -t vfat -o rw,nosuid,nodev,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=utf8,showexec,uid=1000,gid=1000 /dev/disk/by-uuid/3166-6338 /media/simone/sandisk_u
    expect "password"
    send "$password\r"
  }

  if {$sdv == 1 && $wcv == 0} {
    puts "\n\n+vvv+"
    sleep 0.5
    spawn sudo mount -o rw,nosuid,nodev,relatime,data=ordered,uhelper=udisks2 /dev/disk/by-uuid/d042e951-6889-412c-8b0d-c792593f7b20 /media/simone/sandisk_v
    expect "password"
    send "$password\r"
  }

  if {$sdw == 1 && $wcw == 0 && $exist_sdw_src == 1} {
    puts "\n\n+www+"
    sleep 0.5
    spawn sudo mount -o rw,nosuid,nodev,relatime,stripe=32696,data=ordered,uhelper=udisks2 /dev/disk/by-uuid/3534-6562 /media/simone/sandisk_w
    #spawn sudo mount -o rw,nosuid,nodev,relatime,data=ordered /dev/disk/by-label/udisk_hama /media/simone/sandisk_w
    expect "password"
    send "$password\r"
  }

  if {$sdx == 1 && $wcx == 0} {
    puts "\n\n+xxx1+"
    sleep 0.5
    spawn sudo mount -o rw,nosuid,nodev,relatime,stripe=32696,data=ordered,uhelper=udisks2 /dev/disk/by-label/sandisk_ext /media/simone/sandisk_x1
    expect "password"
    send "$password\r"

    puts "\n\n+xxx2+"
    sleep 0.5
    spawn sudo mount -o rw,nosuid,nodev,relatime,stripe=32696,data=ordered,uhelper=udisks2 /dev/disk/by-label/sandisk_exp /media/simone/sandisk_x2
    expect "password"
    send "$password\r"
  }

  expect eof
EOD
