#!/bin/bash

#[[ -z "$DISPLAY" ]] && SID=0 || SID=1
#
#tmux has-session -t $SID
#if [ $? -ne 0 ]; then
#    exit 0
#fi

while getopts "npsStx" opt; do
    case $opt in
        n) action="next";;
        p) action="previous";;
        s) action="seek +10";;
        S) action="seek -10";;
        t) action="toggle-pause";;
        x) action="stop";;
        ?) echo 'Usage: musdo [-npsStx]'
           exit 1;;
    esac
done

#{{{
#state=$(mocp -i | grep "State:" | cut -d' ' -f2)
#if [[ action =~ "toggle" ]]; then
#    if [[ $state =~ "PLAY" ]]; then
#        action="pause"
#    elif [[ $state =~ "PAUSE" ]]; then
#        action="unpause"
#    else
#        action="play"
#    fi
#fi
#}}}

mocp --$action
exit 0

# vim: foldmethod=marker
