#!/bin/bash

[[ -z "$DISPLAY" ]] && SID=0 || SID=1

tmux has-session -t $SID
if [ $? -ne 0 ]; then
    exit 0
fi

while getopts "pnsPu" opt; do
    case $opt in
        p) action="previous";;
        n) action="next";;
        s) action="stop";;
        P) action="pause";;
        u) action="unpause";;
        ?) echo 'Usage: musdo [-pnsPu]'
           exit 1;;
    esac
done

mocp --$action
exit 0
