#!/bin/bash

[[ -z "$DISPLAY" ]] && SID=0 || SID=1

tmux has-session -t $SID
if [ $? -ne 0 ]; then
    exit 0
fi

while getopts "pnst" opt; do
    case $opt in
        p) action="previous";;
        n) action="next";;
        s) action="stop";;
        t) action="toggle-pause";;
        ?) echo 'Usage: musdo [-pnst]'
           exit 1;;
    esac
done

#state=$(mocp -i | grep "State:" | cut -d' ' -f2)
#if [[ action =~ "toggle" ]]; then
#    if [[ $state =~ "PLAY" ]]; then
#        action="pause"
#    elif [[ $state =~ "PAUSE" ]]; then
#        action="unpause"
#    else
#        action="play"
#    fi
#fi

mocp --$action
exit 0
