#!/bin/bash

if [ -z "$DISPLAY" ]; then
    CMD="mocp"
else
    CMD="ncmpc -f ~/.config/ncmpc/config -k ~/.config/ncmpc/keys"
fi

[[ -z "$DISPLAY" ]] && SID=0 || SID=1
[[ ! "$TERM" =~ "screen" ]] && SID=13    #not in tmux session
WID=6
WIN="music"

while getopts "bd" opt; do
    case $opt in
        d)
            OPTS="-d"
            WID=13
            WIN="asmr"
            if [ ! -z "$DISPLAY" ]; then
                exit 0
            fi
            ;;
        b)
            if [ -z "$DISPLAY" ]; then
                CMD="ncmpc -f ~/.config/ncmpc/config -k ~/.config/ncmpc/keys"
            else
                CMD="mocp"
            fi
            ;;

        ?)  echo 'Usage: musmux [-bd]'
            exit 1;;
    esac
done
shift $((OPTIND-1))

tmux has-session -t $SID 2>/dev/null
if [ $? -ne 0 ]; then
    $CMD
    exit 0
fi

tmux select-window -t $SID:$WIN > /dev/null 2>&1
if [ $? -ne 0 ]; then
    tmux new-window $OPTS -n $WIN -t $SID:$WID "stty -ixon; $CMD"
    if [[ "$CMD" =~ "mocp" ]]; then
        if [ -z "$DISPLAY" ]; then
            tmux send-keys -t $SID:$WID "/fave" C-m
            tmux send-keys -t $SID:$WID w

            if [[ "$WIN" =~ "asmr" ]]; then
                tmux send-keys -t $SID:$WID "=/opt/.porn/asmr" C-m
                exit 0
            fi
        fi
    #    tmux send-keys -t $SID:$WID M
    #    tmux send-keys -t $SID:$WID C-i
    #    tmux send-keys -t $SID:$WID "/misc" C-m
    #    tmux send-keys -t $SID:$WID G
    #    tmux send-keys -t $SID:$WID C-i
    #    #sleep 1s
    #    #tmux split-window -v
    #    #tmux send-keys -t $SID:$WID "ccal -u" C-m
    #    #tmux select-pane -l
    #    #tmux split-window -h "tty-clock -c -C 3"
    #    #tmux resize-pane -R 16
    #    #tmux select-pane -L
    #    #tmux swap-pane -D
    fi

    #if [[ "$CMD" =~ "ncmpc" ]]; then
    #    tmux send-keys -t $SID:$WID M
    #    tmux split-window -h -t $SID:$WID
    #    tmux send-keys -t $SID:$WID "cd ~/auds" C-m
    #    tmux send-keys -t $SID:$WID "fd -t=f -e=mp3 . ~/auds | sed -e 's#.*/auds/##' | fzf --height=0 --inline-info --bind 'ctrl-d:execute(tmux killp)' --bind 'ctrl-o:execute-silent(fzfopen {})'" C-m
    #    tmux select-pane -l -t $SID:$WID
    #fi
fi

exit 0
