#!/bin/bash

SID=0
WID=2
WIN="newsbeuter"
CMD="newsbeuter -q"

if [ ! -z "$DISPLAY" ]; then
    $CMD
    exit 0
fi

tmux has-session -t $SID
if [ $? -ne 0 ]; then
    $CMD
    exit 0
fi

tmux select-window -t $WIN > /dev/null 2>&1
if [ $? -ne 0 ]; then
    tmux new-window -n $WIN -t $SID:$WID $CMD
fi

exit 0
