#!/bin/bash

[ ! -f /opt/.priv/password ] && exit 1

password="$(< /opt/.priv/password)"

#/usr/bin/expect <(cat << EOD
/usr/bin/expect << EOD
    set timeout 30
    spawn sudo mount -t exfat -o rw,nosuid,nodev,relatime,,user_id=0,group_id=0,default_permissions,allow_other,blksize=4096 /dev/disk/by-uuid/EA1D-0944 /media/simone/sandisk_s
    expect "password"
    send "$password\r"
    expect eof
EOD
#)
