#!/bin/bash

password="$(< /opt/.priv/password)"

#/usr/bin/expect <(cat << EOD
/usr/bin/expect << EOD
    set timeout 30
    spawn sudo mount -o rw,nosuid,nodev,relatime,data=ordered /dev/disk/by-label/udisk_hama /media/simone/sandisk_w
    expect "password"
    send "$password\r"
    expect eof
EOD
#)
