#!/bin/bash

[ ! -f /opt/.priv/password ] && exit 1

PRIV=1

while getopts "p" opt; do
    case $opt in
        p)
           PRIV=0
           ;;
        ?)
           echo 'sandisk -[p]'
           exit 1;;
    esac
done

shift $((OPTIND-1))  #This tells getopts to move on to the next argument.

password="$(< /opt/.priv/password)"
passphrase="$(< /opt/.priv/passphrase)"

/usr/bin/expect << EOD
    set timeout 3

    spawn sudo mount -t ecryptfs /opt/.porn/text /opt/.porn/text -o ecryptfs_cipher=aes,ecryptfs_key_bytes=16,ecryptfs_passthrough=n,ecryptfs_enable_filename_crypto=y,ecryptfs_fnek_sig=85e5a0a7dcf6b743
    expect "password"
    send "$password\r"
    expect "Passphrase"
    send "$passphrase\r"

    sleep 0.5
    spawn sudo mount -t vfat -o rw,nosuid,nodev,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=utf8,showexec,uid=1000,gid=1000 /dev/disk/by-uuid/3166-6338 /media/simone/sandisk_u
    expect "password"
    send "$password\r"
    expect eof

    sleep 0.5
    spawn sudo mount -o rw,nosuid,nodev,relatime,data=ordered,uhelper=udisks2 /dev/disk/by-uuid/d042e951-6889-412c-8b0d-c792593f7b20 /media/simone/sandisk_v
    expect "password"
    send "$password\r"

    sleep 0.5
    spawn sudo mount -o rw,nosuid,nodev,relatime,data=ordered /dev/disk/by-label/udisk_hama /media/simone/sandisk_w
    expect "password"
    send "$password\r"

    sleep 0.5
    spawn sudo mount -o rw,nosuid,nodev,relatime,stripe=32696,data=ordered,uhelper=udisks2 /dev/disk/by-label/sandisk_ext /media/simone/sandisk_x1
    expect "password"
    send "$password\r"

    sleep 0.5
    spawn sudo mount -o rw,nosuid,nodev,relatime,stripe=32696,data=ordered,uhelper=udisks2 /dev/disk/by-label/sandisk_exp /media/simone/sandisk_x2
    expect "password"
    send "$password\r"

    expect eof
EOD

[ $PRIV -eq 0 ] && exit 0

/usr/bin/expect << EOD
    set timeout 3

    sleep 0.5
    spawn sudo umount /opt/.priv
    expect "password"
    send "$password\r"

    expect eof
EOD
