#!/bin/bash

### getopts {{{
OPTS=""
POPS=0
TEMP=0
MOVE=0
CYCLE=0
while getopts "BMPTY" opt; do
    case $opt in
        B)  OPTS="-B" ;;
        M)  MOVE=1    ;;
        P)  POPS=1    ;;
        T)  TEMP=1    ;;
        Y)  CYCLE=1   ;;
        ?)  echo 'Usage: scratchpad [-BMPTY]'
            exit 1;;
    esac
done
shift $((OPTIND-1))
### }}}

### tmux in i3wm {{{
if [[ ! -z $DISPLAY ]]; then
    if [[ "$I3_SCRATCHPAD" == "YES" ]]; then
        tmux -L x-serv has-session -t nova 2>/dev/null && \
            tmux -L x-serv attach-s -t nova && exit 0
        tmux -L x-serv new-session -s nova -n nova vifmrun
    fi

    exit 0
fi
### }}}

### tmux in fbterm {{{
SID="${1:-pops}"
APP="${2:-fffm}"
WIDTH=${3:-81%}
HEIGHT=${4:-64%}

CURR_SID=$(tmux display-message -p -F '#{session_name}')
CURR_WID=$(tmux display-message -p -F '#{window_index}')

if [ $POPS -eq 1 ]; then
    if [[ "$(tmux display-message -p -F '#{session_name}')" == $SID ]]; then
        tmux detach-client
    else
        tmux popup $OPTS -E -w$WIDTH -h$HEIGHT "tmux attach-s -t $SID || tmux new-s -s $SID $APP"
    fi

    exit 0
fi

if [ $MOVE -eq 1 ]; then
    tmux popup $OPTS -E -w 80% -h 80% "tmux attach-s -t temp || \
        (tmux new-s -d -s temp && tmux move-w -s $CURR_SID:$CURR_WID -t temp)"
    exit 0
fi

if [ $TEMP -eq 1 ]; then
    if [[ "$CURR_SID" == "temp" ]]; then
        tmux detach-client
    else
        tmux popup $OPTS -E -w 80% -h 80% "tmux attach-s -t temp"
    fi

    exit 0
fi

if [ $CYCLE -eq 1 ]; then  ### {{{
    if [[ $CURR_SID == 0 ]]; then
        tmux has-session -t asmr 2>/dev/null && tmux popup -BE -w64% -h64% "tmux attach-s -t asmr" && exit 0
        tmux has-session -t nova 2>/dev/null && tmux popup -E  -w81% -h64% "tmux attach-s -t nova" && exit 0
        tmux has-session -t temp 2>/dev/null && tmux popup -E  -w80% -h80% "tmux attach-s -t temp" && exit 0
        exit 0
    fi

    if [[ "$CURR_SID" == "asmr" ]]; then
        tmux detach-client -s asmr
        tmux has-session -t nova 2>/dev/null && tmux popup -E  -w81% -h64% "tmux attach-s -t nova" && exit 0
        tmux has-session -t temp 2>/dev/null && tmux popup -E  -w80% -h80% "tmux attach-s -t temp" && exit 0
        exit 0
    fi

    if [[ "$CURR_SID" == "nova" ]]; then
        tmux detach-client -s nova
        tmux has-session -t temp 2>/dev/null && tmux popup -E  -w80% -h80% "tmux attach-s -t temp" && exit 0
        exit 0
    fi

    if [[ $CURR_SID == "temp" ]]; then
        tmux detach-client -s temp
        tmux has-session -t asmr 2>/dev/null && tmux popup -BE -w64% -h64% "tmux attach-s -t asmr" && exit 0
        tmux has-session -t nova 2>/dev/null && tmux popup -E  -w81% -h64% "tmux attach-s -t nova" && exit 0
        exit 0
    fi

    exit 0
fi
### }}}

exit 0
### }}}

### For tmux-3.0a(/opt/misc/appimg/tmux.appimage) {{{
tmux -L default has-session -t 13 2>/dev/null || tmux new-s -d -s 13 "clear; screenfetch"

#nova_cmd="fffm /opt/.porn/text"
nova_cmd="ranger /opt/.porn/text"
tmux list-w -t 13 2>/dev/null | grep nova > /dev/null || tmux new-w -n nova -t 13:11 $nova_cmd

asmr_cmd="mocp /opt/.porn/asmr"
tmux list-w -t 13 2>/dev/null | grep asmr > /dev/null || tmux new-w -n asmr -t 13:13 $asmr_cmd
#tmux send-keys -t 13:asmr "/asmr.m3u" C-m
#[[ -f /opt/.porn/asmr/asmr.m3u ]] && mocp -a /opt/.porn/asmr/asmr.m3u

exit 0
### }}}

### For reference {{{
#scratchlist=$('i3-msg -t get_tree | jq ".nodes|.[]|.|.nodes|.[]|.nodes|.[]|select(.name==\"__i3_scratch\")|.floating_nodes|.[]|.nodes|.[]|.window_properties.class"')
#"nova"
#"asmr"

#curr_scratchpad=$('i3-msg -t get_tree | jq ".nodes|.[]|.|.nodes|.[]|.nodes|.[]|select(.name==\"__i3_scratch\")|.floating_nodes|.[]|.nodes|.[]|select(.focused==true).window_properties.class"')
#[[ -z $curr_scratchpad ]] && i3-msg workspace misc

#ScratchHasNova=$(i3-msg -t get_tree | jq '.nodes[].nodes[].nodes[] | .type == "workspace" and .name =="__i3_scratch" and .floating_nodes[].nodes[].window_properties.class == "nova"' | grep -q true)

#curr_workspace=$(i3-msg -t get_workspaces | jq '.[] | select(.focused==true).name')
#[[ $curr_workspace =~ "term" ]] && i3-msg workspace misc
### }}}

# vim: set foldmethod=marker:
