#!/bin/bash

mkdir ~/auds
mkdir ~/docs
mkdir ~/misc
mkdir ~/pics
mkdir ~/temp
mkdir ~/vids

mkdir ~/docs/book
mkdir ~/docs/misc
mkdir ~/docs/note
mkdir ~/docs/webs

sudo chown -R simone:simone /opt
mkdir /opt/apps
mkdir /opt/auds
mkdir /opt/conf
mkdir /opt/misc
mkdir /opt/util
mkdir /opt/vids

mkdir /opt/.certs
mkdir /opt/.logs
mkdir /opt/.mail
mkdir /opt/.porn
mkdir /opt/.priv

mkdir /opt/misc/apps
mkdir /opt/misc/docs
mkdir /opt/misc/dicts
mkdir /opt/misc/fonts

mkdir /opt/.porn/te*********

cd ~
git clone https://github.com/phantasea/note note
git clone https://github.com/phantasea/webs webs

cd /opt
git clone https://github.com/phantasea/priv .priv
git clone https://github.com/phantasea/util util
git clone https://github.com/phantasea/misc misc
git clone https://github.com/phantasea/dotfiles conf

cd /opt/apps
git clone https://github.com/phantasea/adbfs
git clone https://github.com/phantasea/autojump
git clone https://github.com/phantasea/elinks
git clone https://github.com/phantasea/fbv
git clone https://github.com/phantasea/fim
git clone https://github.com/phantasea/fzf
git clone https://github.com/phantasea/htop
git clone https://github.com/phantasea/jfbview
git clone https://github.com/phantasea/moc
git clone https://github.com/phantasea/myst
git clone https://github.com/phantasea/pho
git clone https://github.com/phantasea/ranger
git clone https://github.com/phantasea/vifm
git clone https://github.com/phantasea/w3m

ln -sf /opt/.mail                            ~/.mail
ln -sf /opt/.logs                            ~/.logs
ln -sf /opt/.priv/fetchmailrc                ~/.fetchmailrc
ln -sf /opt/.priv/msmtprc                    ~/.msmtprc
ln -sf /opt/util                             ~/.util
ln -sf /opt/apps/fzf                         ~/.fzf
ln -sf /opt/misc/fonts                       ~/.fonts
ln -sf /opt/misc/dicts                       ~/.stardict/dic
ln -sf /opt/conf/wallpaper                   ~/.wallpaper
ln -sf /opt/conf/mailcap                     ~/.mailcap
ln -sf /opt/conf/inputrc                     ~/.inputrc
ln -sf /opt/conf/vim                         ~/.vim
ln -sf /opt/conf/vim/vimrc                   ~/.vimrc
ln -sf /opt/conf/alias                       ~/.alias
ln -sf /opt/conf/bashrc                      ~/.bashrc
ln -sf /opt/conf/fbtermrc                    ~/.fbtermrc
ln -sf /opt/conf/tmux.conf                   ~/.tmux.conf
ln -sf /opt/conf/fzf.bash                    ~/.fzf.bash
ln -sf /opt/conf/forgit.bash                 ~/.forgit.bash
ln -sf /opt/conf/hhighlighter.sh             ~/.hhighlighter.sh
ln -sf /opt/conf/fimrc                       ~/.fimrc
ln -sf /opt/conf/dircolors                   ~/.dircolors
ln -sf /opt/conf/moc                         ~/.moc
ln -sf /opt/conf/mplayer/                    ~/.mplayer
ln -sf /opt/conf/vifm/                       ~/.vifm
ln -sf /opt/conf/w3m/                        ~/.w3m
ln -sf /opt/conf/git/gitconfig               ~/.gitconfig
ln -sf /opt/conf/abookrc                     ~/.abookrc
ln -sf /opt/conf/dictrc                      ~/.dictrc
ln -sf /opt/conf/elinks.conf                 ~/.elinks/elinks.conf
ln -sf /opt/conf/newsbeuter/                 ~/.newsbeuter
ln -sf /opt/conf/yong                        ~/.yong
ln -sf /opt/conf/mutt                        ~/.mutt
ln -sf /opt/conf/muttrc                      ~/.muttrc
ln -sf /opt/conf/procmailrc                  ~/.procmailrc
ln -sf /opt/conf/signature                   ~/.signature
ln -sf /opt/conf/tigrc                       ~/.tigrc
ln -sf /opt/conf/task                        ~/.task
ln -sf /opt/conf/taskrc                      ~/.taskrc
ln -sf /opt/conf/urlview                     ~/.urlview
ln -sf /opt/conf/vnstatrc                    ~/.vnstatrc
ln -sf /opt/conf/wgetrc                      ~/.wgetrc
ln -sf /opt/conf/apvlvrc                     ~/.apvlvrc
ln -sf /opt/conf/goto.sh                     ~/.goto.sh
ln -sf /opt/conf/user-dirs.dirs              ~/.config/user-dirs.dirs
ln -sf /opt/conf/user-dirs.locale            ~/.config/user-dirs.locale
ln -sf /opt/conf/feh                         ~/.config/feh
ln -sf /opt/conf/mpv                         ~/.config/mpv
ln -sf /opt/conf/ranger/                     ~/.config/ranger
ln -sf /opt/conf/zathura                     ~/.config/zathura
ln -sf /opt/conf/compton.conf                ~/.config/compton.conf
ln -sf /opt/conf/vimb/config                 ~/.config/vimb/config
ln -sf /opt/conf/vimb/style.css              ~/.config/vimb/style.css
ln -sf /opt/conf/i3/config                   ~/.config/i3wm/i3.config
ln -sf /opt/conf/i3status/config             ~/.config/i3wm/i3status.config
ln -sf /opt/conf/bat.config                  ~/.config/bat/config
ln -sf /opt/conf/streamlink.config           ~/.config/streamlink/config
ln -sf /opt/auds                             ~/auds/auds

ln -sf /usr/local/porn                       /opt/.porn/porn

sudo ln -sf /opt/conf/updatedb.conf          /etc/updatedb.conf
sudo ln -sf /opt/conf/51-android.rules       /etc/udev/rules.d/51-android.rules
sudo ln -sf /opt/conf/locale.nopurge         /etc/locale.nopurge
sudo ln -sf /opt/conf/sources.list           /etc/apt/sources.list

sudo cp -f  /opt/conf/rc.local               /etc/rc.local

exit 0
