#!/bin/bash

if [ -z "$DISPLAY" ]; then
    SID=0
else
    SID=1
fi

WID=2
WIN="tig"
CMD="tig"

file=$1
file=${file// /\\\ }

tmux has-session -t $SID
if [ $? -ne 0 ]; then
    $CMD $file
    exit 0
fi

tmux select-window -t $SID:$WIN > /dev/null 2>&1
if [ $? -ne 0 ]; then
    tmux new-window -n $WIN -t $SID:$WID "setterm -cursor off; $CMD $file"
fi

exit 0
