#!/bin/bash

SID=0
WID=2
WIN="tig"
CMD="tig"

file=$1
file=${file// /\\\ }

if [ ! -z "$DISPLAY" ]; then
    $CMD $file
    exit 0
fi

tmux has-session -t $SID
if [ $? -ne 0 ]; then
    $CMD $file
    exit 0
fi

tmux select-window -t $WIN > /dev/null 2>&1
if [ $? -ne 0 ]; then
    tmux new-window -n $WIN -t $SID:$WID "setterm -cursor off; $CMD $file"
fi

exit 0
