#!/bin/bash

#if rfkill list bluetooth | grep "Soft blocked: no" ; then
#    rfkill block bluetooth ;
#else
#    rfkill unblock bluetooth ;
#fi

MAC=$(bluetoothctl devices | grep BUDS | cut -d' ' -f2)
if bluetoothctl info $MAC | grep 'Connected: yes' ; then
    bluetoothctl disconnect $MAC
else
    if bluetoothctl info $MAC | grep 'Blocked: no' ; then
        bluetoothctl connect $MAC
    fi
fi
