#!/bin/bash

[[ $(synclient -l | grep TouchpadOff | cut -d '=' -f 2) -eq 0 ]] && synclient TouchpadOff=1 || synclient TouchpadOff=0

#if synclient -l | grep "TouchpadOff .*=.*0" ; then
#    synclient TouchpadOff=1 ;
#else
#    synclient TouchpadOff=0 ;
#fi
