#!/bin/bash

if [ ! -f "$1" ]; then
    echo $1
    echo 'is not a file!'
    exit 1
fi

#which uchardet > /dev/null
#if [[ ! $? -eq 0 ]]; then
if ! command -v uchardet > /dev/null 2>&1; then
    echo "sudo apt install uchardet"
    exit 2
fi

icode=$(uchardet "$1")
#file -bi "$1"
#chardet "$1"
#echo "$icode"

#icode=$(file -bi "$1")
#icode="utf8"
if [ ! -z "$2" ]; then
    icode="$2"
fi

filename=$(basename -- "$1")
fileext="${filename##*.}"
filebase="${filename%.*}"
#echo $filename

shopt -s nocasematch
if [[ "$fileext" != "txt" ]]; then
    echo $1, $fileext
    echo "Not ***.txt file!"
    exit 3
fi

filepath=$(realpath -- "$1")
dirname=$(dirname -- "$filepath")
#echo $dirname
cd -- "$dirname"

ebook-convert "$filename" "$filebase".epub \
        --input-encoding="$icode" \
        --no-default-epub-cover \
        --flow-size=0 \
        --dont-split-on-page-breaks \
        --enable-heuristics \
        --page-breaks-before=/ --chapter=/  >/dev/null

#       --line-height=1 \


#~% FILE="example.tar.gz"
#~% echo "${FILE%%.*}"
#   example
#~% echo "${FILE%.*}"
#   example.tar
#~% echo "${FILE#*.}"
#   tar.gz
#~% echo "${FILE##*.}"
#   gz
