#!/bin/bash

[ ! -f /opt/.priv/password ] && exit 1

password="$(< /opt/.priv/password)"

#/usr/bin/expect <(cat << EOD
/usr/bin/expect << EOD
    set timeout 30
    spawn sudo umount /opt/.priv
    expect "password"
    send "$password\r"
    expect eof
EOD
#)
