#!/bin/bash

if [ -z "$DISPLAY" ]; then
    SID=0
    CMD="mplayer"
else
    SID=1
    CMD="mpv"
fi

WID=6
WIN="video"
NOFS=""

while getopts "n" opt; do
    case $opt in
        n)
           NOFS="-nofs -xy 768"
           ;;
        ?)
           echo 'Usage0: vidmux [-n] file'
           exit 1;;
    esac
done

shift $((OPTIND-1))  #This tells getopts to move on to the next argument.

if [ $# -gt 1 ] || [ $# -eq 0 ]; then
    echo 'Usage1: vidmux file'
    exit 1
fi

if [ ! -f "$1" ]; then
    echo 'Usage2: vidmux file'
    exit 1
fi

tmux has-session -t $SID
if [ $? -ne 0 ]; then
    setterm -cursor off; $CMD $NOFS "$1"
    exit 0
fi

tmux select-window -t $SID:$WIN > /dev/null 2>&1
if [ $? -ne 0 ]; then
    tmux new-window -n $WIN -t $SID:$WID "setterm -cursor off; $CMD $NOFS \"$1\""
fi

exit 0
