#!/bin/bash

[[ -z "$DISPLAY" ]] && SID=0 || SID=1
[[ ! "$TERM" =~ "screen" ]] && SID=12    #not in tmux session
[[ $(tmux ls | egrep "13:.*attached") ]] && SID=13
WID=5
WIN="vidplay"

[[ -z "$DISPLAY" ]] && CMD="mplayer" || CMD="mpv 2>/dev/null"

while getopts "bB" opt; do
    case $opt in
        B)
            if [[ $CMD =~ "mplayer" ]]; then
                CMD+=" -nofs -xy 768"
            else
                CMD+=" --no-fs 2>/dev/null"
            fi
            ;;
        b)
            if [ -z "$DISPLAY" ]; then
                CMD="mpv --vo=drm 2>/dev/null"
            else
                CMD="mplayer -vo x11"
            fi
            ;;
        ?)
            echo 'Usage: vidmux [-bB] <file>'
            exit 1;;
    esac
done

#echo $CMD

shift $((OPTIND-1))  #This tells getopts to move on to the next argument.

if [ $# -gt 1 ] || [ $# -eq 0 ]; then
    echo 'Usage1: vidmux [-bB] <file>'
    exit 1
fi

if [ ! -f "$1" ]; then
    echo 'Usage2: vidmux [-bB] <file>'
    exit 1
fi

size=$(stat -c %s -- "$1")
if [[ $size -lt 10000000 ]] && [[ -z "$DISPLAY" ]]; then
    CMD="mpv --vo=drm 2>/dev/null"
fi

FILES=""
if [[ $CMD =~ "mplayer" ]]; then
    FILES="*.mp4"
fi

# cannot switch between mpv and other window
tmux has-session -t $SID 2>/dev/null
if [[ $? -ne 0 ]] || [[ $CMD =~ "mpv" ]] || [[ ! -z "$DISPLAY" ]]; then
    $CMD "$1" $FILES 2>/dev/null &
    exit 0
fi

# only mplayer in console goes here
tmux select-window -t $SID:$WIN > /dev/null 2>&1
if [ $? -ne 0 ]; then
    tmux new-window -n $WIN -t $SID:$WID "setterm -cursor off; $CMD \"$1\" $FILES"
fi

exit 0
