#!/bin/bash

if [ -z "$DISPLAY" ]; then
    CMD="mplayer"
else
    CMD="mpv"
fi

SID=0
WID=5
WIN="vidplay"

[[ ! -z "$DISPLAY" ]] && SID=1

# not in tmux session
[[ ! "$TERM" =~ "screen" ]] && SID=13

while getopts "bB" opt; do
    case $opt in
        b)
            if [[ $CMD =~ "mplayer" ]]; then
                CMD+=" -nofs -xy 768"
            else
                CMD+=" --no-fs"
            fi
            ;;
        B)
            if [ -z "$DISPLAY" ]; then
                CMD="mpv --vo=drm"
            else
                CMD="mplayer -vo x11"
            fi
            ;;
        ?)
            echo 'Usage: vidmux [-bB] <file>'
            exit 1;;
    esac
done

#echo $CMD

shift $((OPTIND-1))  #This tells getopts to move on to the next argument.

if [ $# -gt 1 ] || [ $# -eq 0 ]; then
    echo 'Usage1: vidmux [-bB] <file>'
    exit 1
fi

if [ ! -f "$1" ]; then
    echo 'Usage2: vidmux [-bB] <file>'
    exit 1
fi

tmux has-session -t $SID 2>/dev/null
if [ $? -ne 0 ]; then
    $CMD "$1"
    exit 0
fi

tmux select-window -t $SID:$WIN > /dev/null 2>&1
if [ $? -ne 0 ]; then
    tmux new-window -n $WIN -t $SID:$WID "setterm -cursor off; $CMD \"$1\""
fi

exit 0
