#!/bin/bash

if [ -z "$DISPLAY" ]; then
    vifm
    exit 0
fi

if [ -z "$(command -v vifm)" ]; then
    printf "vifm isn't installed on your system!\n"
    exit 1
elif [ -z "$(command -v ueberzug)" ]; then
    exec vifm --server-name vifm-gui "$@"
else
    cleanup() {
        exec 3>&-
        rm "$FIFO_UEBERZUG"
    }

    [ ! -d "/tmp/vifm" ] && mkdir -p "/tmp/vifm"
    export FIFO_UEBERZUG="/tmp/vifm/ueberzug-${$}"
    mkfifo "$FIFO_UEBERZUG"

    ueberzug layer -s <"$FIFO_UEBERZUG" -p json &
    exec 3>"$FIFO_UEBERZUG"
    trap cleanup EXIT

    vifm --server-name vifm-gui "$@" 3>&-
    vifmimg clear
fi
