#!/bin/sh

if [ -z "$DISPLAY" ]; then
    vifm
    exit 0
fi

if [ -z "$(command -v ueberzug)" ]; then
    exec vifm "$@"
else
    cleanup() {
        exec 3>&-
        rm "$FIFO_UEBERZUG"
    }

    [ ! -d "/tmp/vifm" ] && mkdir -p "/tmp/vifm"
    export FIFO_UEBERZUG="/tmp/vifm/ueberzug-${$}"
    mkfifo "$FIFO_UEBERZUG"

    ueberzug layer -s <"$FIFO_UEBERZUG" -p json &
    exec 3>"$FIFO_UEBERZUG"
    trap cleanup EXIT

    vifm "$@" 3>&-
    vifmimg clear
fi
