#!/bin/bash

file=$*
#file=${file// /\\\ }

if [[ ! -f "$file" ]] && [[ ! -d "$file" ]]; then
    if [[ ! -f "$1" ]] && [[ ! -d "$1" ]]; then
        exit
    fi

    file=$1
fi

cmd="goto"
if [[ -d "$file" ]]; then
    cmd="cd"
fi

[[ -z "$DISPLAY" ]] && SERV='vifm-tty' || SERV='vifm-gui'
vifm --server-name $SERV --remote -c "$cmd \"$file\""

exit 0
