#!/bin/bash

file=$*
#file=${file// /\\\ }

if [[ ! -f "$file" ]]; then
    if [[ ! -f "$1" ]]; then
        exit
    fi

    file=$1
fi

[[ -z "$DISPLAY" ]] && SERV='vifm-tty' || SERV='vifm-gui'
vifm --server-name $SERV --remote -c "edit \"$file\""

exit 0
