#! /bin/bash

SESSION=0

prog="vim"
exe="edit"
diff=0

WIN="vim"
SID=7

while getopts "vc:d" opt; do
    case $opt in
        v) 
           prog="view"
           exe="view"
           ;;
        c) cmd="$OPTARG";;
        d) 
           diff=1
           prog="vimdiff"
           WIN="diff"
           SID=0
           ;;
        ?) echo 'Usage0: vimux [-v]/[-d]/[-c cmd] file/dir'
           exit 1;;
    esac
done

shift $((OPTIND-1))  #This tells getopts to move on to the next argument.

#echo $#
#echo $*
#echo $@
#while [ $# -ne 0 ]; do
#    echo $1
#    shift
#done
##vim $*
#exit 0

#if [ $# -eq 0 -o $# -gt 1 ]; then
#    echo $*
#    echo 'Usage1: vimux [-v] [-c cmd] file/dir'
#    exit 1
#fi

if [ ! -f "$1" ] && [ ! -d "$1" ]; then
    echo $1
    echo 'Usage2: vimux [-v] [-c cmd] file/dir'
    exit 1
fi

file=$1
file=${file// /\\\ }

tmux has-session -t $SESSION
if [ $? -ne 0 ] || [ ! -z "$DISPLAY" ]; then
    $prog $file
    exit 0
fi

cwd=$PWD
cwd=${cwd// /\\\ }

file2=""
if [ -f "$2" ]; then
    file2=$2
    file2=${file2// /\\\ }
fi

tmux select-window -t $WIN > /dev/null 2>&1
if [ $? -ne 0 ]; then
    tmux new-window -n $WIN -t $SESSION:$SID "$prog $file $file2"
    tmux select-window -t $WIN
fi

if [ $diff -eq 1 ]; then
    echo 'tmux window:vimdiff already exists'
    exit 0
fi

tmux send-keys -t $SESSION:$SID escape
tmux set-buffer ":cd $cwd"
tmux paste-buffer -t $SESSION:$SID
tmux send-keys -t $SESSION:$SID C-m

tmux set-buffer ":$exe $file"
tmux paste-buffer -t $SESSION:$SID
tmux send-keys -t $SESSION:$SID C-m

if [ ! -z "$cmd" ]; then
    tmux set-buffer ":$cmd"
    tmux paste-buffer -t $SESSION:$SID
    tmux send-keys -t $SESSION:$SID C-m
fi

exit 0
