#! /bin/bash

if [ -z "$DISPLAY" ]; then
    SID=0
else
    SID=1
fi

if [[ ! "$TERM" =~ "screen" ]]; then
    SID=13
fi

WID=7
WIN="vim"

#prog="vim"
prog="nvim"
exe="edit"
diff=0

while getopts "vc:ds:" opt; do
    case $opt in
        v) 
           #prog="view"
           prog="nvim -R"
           exe="view"
           ;;
        c) cmd="$OPTARG";;
        d) 
           diff=1
           #prog="vimdiff"
           prog="nvim -d"
           WIN="diff"
           WID=0
           ;;
        s)
           search="$OPTARG"
           ;;

        ?) echo 'Usage: vimux [-v]/[-d]/[-c cmd]/[-s search] file/dir'
           exit 1;;
    esac
done

shift $((OPTIND-1))  #This tells getopts to move on to the next argument.

#echo "$search" " | " "$1"

if [ ! -f "$1" ] && [ ! -d "$1" ]; then
    echo $1
    echo 'is neither a file nor directory'
    exit 1
fi

maxsize=3000000
#size=$(wc -c < "$1")
#size=$(stat --printf="%s" "$1")
size=$(stat -c %s -- "$1")
if [ $size -gt $maxsize ]; then
    echo "file size $size is large than $maxsize!"
    exit 1
fi

file=$1
file=${file// /\\\ }
file=${file//(/\\\(}
file=${file//)/\\\)}

tmux has-session -t $SID 2>/dev/null
if [ $? -ne 0 ]; then
    $prog $file
    exit 0
fi

cwd=$PWD
cwd=${cwd// /\\\ }

file2=""
if [ -f "$2" ]; then
    file2=$2
    file2=${file2// /\\\ }
    file2=${file2//(/\\\(}
    file2=${file2//)/\\\)}
fi

tmux select-window -t $SID:$WIN > /dev/null 2>&1
if [ $? -ne 0 ]; then
    tmux new-window -n $WIN -t $SID:$WID "stty -ixon; $prog $file $file2"
    tmux select-window -t $SID:$WIN
    exit 0
fi

if [ $diff -eq 1 ]; then
    #echo $prog $file $file2
    exit 0
fi

tmux send-keys -t $SID:$WID escape
tmux set-buffer ":cd $cwd"
tmux paste-buffer -t $SID:$WID
tmux send-keys -t $SID:$WID C-m

tmux set-buffer ":$exe $file"
tmux paste-buffer -t $SID:$WID
tmux send-keys -t $SID:$WID C-m

if [ ! -z "$cmd" ]; then
    tmux set-buffer ":$cmd"
    tmux paste-buffer -t $SID:$WID
    tmux send-keys -t $SID:$WID C-m
fi

if [ ! -z "$search" ]; then
    tmux set-buffer "/\V$search"
    tmux paste-buffer -t $SID:$WID
    tmux send-keys -t $SID:$WID C-m
fi

exit 0
