#!/bin/bash
# Draw an image file on the screen using w3m-img.

file="$1"
 
W3M_XOFFSET=0
W3M_YOFFSET=0

# Find supported 'file' arguments.
file -I &>/dev/null || : "${file_flags:=biL}"

# We can use the framebuffer; set win_info_cmd as appropriate.
[[ -z $DISPLAY && -w /dev/fb0 ]] &&
    win_info_cmd=fbset

# X isn't running and we can't use the framebuffer, do nothing.
[[ -z $DISPLAY && $win_info_cmd != fbset ]] && {
    echo "error: not in X and cannot use framebuffer!"
    exit 1
}

# File isn't an image file, do nothing.
mime_type=$(file "-${file_flags:-biL}" "${file}" 2>/dev/null)
[[ $mime_type != image/* ]] && {
    echo "error: \"$file\" is not an image file!"
    exit 1
}

# Get terminal size ('stty' is POSIX and always available).
# This can't be done reliably across all bash versions in pure bash.
read -r LINES COLUMNS < <(stty size)

# Find the path to the w3m-img library.
w3m_paths=(/usr/{local/,}{lib,libexec,lib64,libexec64}/w3m/w3mi*)
read -r w3m _ < <(type -p w3mimgdisplay "${w3m_paths[@]}")

# w3m-img isn't installed, do nothing.
type -p "$w3m" &>/dev/null || {
    echo "error: Couldn't find 'w3m-img', is it installed?"
    exit 1
}

# win_info_cmd isn't installed, do nothing.
type -p "${win_info_cmd:=xdotool}" &>/dev/null || {
    echo "error: Couldn't find '$win_info_cmd', is it installed?"
    exit 1
}

# Get terminal window size in pixels and set it to WIDTH and HEIGHT.
if [[ $win_info_cmd == xdotool ]]; then
    IFS=$'\n' read -d "" -ra win_info \
        < <(xdotool getactivewindow getwindowgeometry --shell)

    declare "${win_info[@]}" &>/dev/null || {
        echo "error: Failed to retrieve window size."
        exit 1
    }
else
    [[ $(fbset --show) =~ .*\"([0-9]+x[0-9]+)\".* ]]
    IFS=x read -r WIDTH HEIGHT <<< "${BASH_REMATCH[1]}"
fi

# Substract the status_line area from the image size.
((HEIGHT=HEIGHT-HEIGHT*2/LINES))

# Get the image size in pixels.
read -r img_width img_height < <("$w3m" <<< "5;${file}")

((img_width > WIDTH)) && {
    ((img_height=img_height*WIDTH/img_width))
    ((img_width=WIDTH))
}

((img_height > HEIGHT)) && {
    ((img_width=img_width*HEIGHT/img_height))
    ((img_height=HEIGHT))
}
#echo $win_info_cmd, $LINES, $WIDTH, $HEIGHT, $img_width, $img_height

# Add a small delay to fix issues in VTE terminals.
#((BASH_VERSINFO[0] > 3)) &&
#    read "${read_flags[@]}" -srn 1

# Display the image.
printf '0;1;%s;%s;%s;%s;;;;;%s\n3;\n4\n' \
    "${W3M_XOFFSET:-0}" \
    "${W3M_YOFFSET:-0}" \
    "$img_width" \
    "$img_height" \
    "${file}" | "$w3m" &>/dev/null

# Wait for user input.
read -ern 1

# Clear the image.
printf '6;%s;%s;%s;%s\n3;' \
    "${W3M_XOFFSET:-0}" \
    "${W3M_YOFFSET:-0}" \
    "$WIDTH" \
    "$HEIGHT" | "$w3m" &>/dev/null
