#! /bin/bash

SESSION=0

execbyranger="FALSE"

while getopts "e" opt; do
    case $opt in
        e) execbyranger="TRUE";;
        ?) echo 'Usage0: w3mux [-e] file'
           exit 1;;
    esac
done

shift $((OPTIND-1))  #This tells getopts to move on to the next argument.

if [ $# -gt 1 ]; then
    echo 'Usage1: w3mux [-e] file'
    exit 1
fi

if [ $# -ne 0 ] && [ ! -f "$1" ]; then
    echo 'Usage2: w3mux [-e] file'
    exit 1
fi

tmux has-session -t $SESSION
if [ $? -ne 0 ] || [ ! -z "$DISPLAY" ]; then
    if [ -z "$1" ]; then
        TERM=jfbterm w3m .
    else
        TERM=jfbterm w3m "$1"
    fi

    exit 0
fi

if [ "$execbyranger" = "FALSE" ]; then
    file="file://$PWD/$1"
else
    file="file://$1"
fi

tmux select-window -t w3m > /dev/null 2>&1
if [ $? -ne 0 ]; then
    tmux new-window -c ~ -n w3m -t $SESSION:8 "TERM=jfbterm w3m \"$file\""
    tmux select-window -t w3m
else
    tmux set-buffer "T $file"
    tmux paste-buffer
    tmux send-keys C-m
fi

exit 0
