#! /bin/bash

#CMD="cd ~; TERM=jfbterm w3m -s"
if [ -z "$DISPLAY" ]; then
    CMD="cd ~/temp; w3m -s"
else
    CMD="cd ~/temp; elinks"
fi

[[ -z "$DISPLAY" ]] && SID=0 || SID=1
[[ ! "$TERM" =~ "screen" ]] && SID=13    #not in tmux session
WID=8
WIN="webview"

bplan=0
while getopts "bBx" opt; do
    case $opt in
        b)
            if [ -z "$DISPLAY" ]; then
                CMD="cd ~/temp; elinks"
            else
                CMD="cd ~/temp; w3m -s"
            fi
            bplan=1
            ;;
        B)
            if [ ! -z "$DISPLAY" ]; then
                if [ $bplan -eq 0 ]; then
                    CMD="firefox"
                else
                    CMD='vimb'
                fi
            fi
            ;;
        x)
            if [ -z "$DISPLAY" ]; then
                CMD="elinks"
            else
                CMD="w3m -s"
            fi
            ;;
        ?)  echo 'Usage: webview [-bBx] URI'
            exit 1;;
    esac
done
shift $((OPTIND-1))

if [ $# -gt 1 ]; then
    echo 'Usage1: webview [-bB] URI'
    exit 1
fi

URI="."
if [ ! -z "$1" ]; then
    if [ -f "$1" ] || [ -d "$1" ]; then
        URI=$(realpath -s "$1")
        URI="file://${URI}"
    else
        URI=$1
        if [[ ! $1 =~ "http" ]]; then
            URI="http://"$URI
        fi
    fi
fi

if [[ $CMD =~ "firefox" ]] || [[ $CMD =~ "vimb" ]]; then
    $CMD "$URI" > /dev/null 2>&1 &
    exit 0
fi

#URI=${URI// /\\\ }
#URI=${URI//(/\\\(}
#URI=${URI//)/\\\)}
#URI=${URI//</\\\<}
#URI=${URI//>/\\\>}
#URI=${URI//|/\\\|}

tmux has-session -t $SID 2>/dev/null
if [ $? -ne 0 ]; then
    setterm -cursor on; $CMD "$URI"
    exit 0
fi

tmux select-window -t $SID:$WIN > /dev/null 2>&1
if [ $? -ne 0 ]; then
    tmux new-window -n $WIN -t $SID:$WID "stty -ixon; $CMD \"$URI\""
    exit 0
fi

tmux send-keys -t $SID:$WID O
tmux set-buffer "$URI"
tmux paste-buffer -t $SID:$WID
tmux send-keys -t $SID:$WID C-m

exit 0
