#! /bin/bash

#CMD="cd ~; TERM=jfbterm w3m -s"
if [ -z "$DISPLAY" ]; then
    SID=0
else
    SID=1
fi

WID=8
WIN="webview"
CMD="cd ~/temp; w3m -s"

while getopts "bB" opt; do
    case $opt in
        b)
            CMD="cd ~/temp; elinks"
            ;;
        B)
            if [ ! -z "$DISPLAY" ]; then
                CMD="firefox"
            fi
            ;;

        ?)  echo 'Usage: wemux [-bB] URI'
            exit 1;;
    esac
done
shift $((OPTIND-1))

if [ $# -gt 1 ]; then
    echo 'Usage1: wemux [-bB] URI'
    exit 1
fi

URI="."
if [ ! -z "$1" ]; then
    if [ -f "$1" ] || [ -d "$1" ]; then
        URI=$(realpath -s "$1")
        URI="file://${URI}"
    else
        URI=$1
        if [[ ! $1 =~ "http" ]]; then
            URI="http://"$URI
        fi
    fi
fi

if [[ $CMD =~ "firefox" ]]; then
    $CMD "$URI" > /dev/null 2>&1 &
    exit 0
fi

tmux has-session -t $SID
if [ $? -ne 0 ]; then
    $CMD "$URI"
    exit 0
fi

tmux select-window -t $SID:$WIN > /dev/null 2>&1
if [ $? -ne 0 ]; then
    tmux new-window -n $WIN -t $SID:$WID "stty -ixon; $CMD \"$URI\""
    exit 0
fi

tmux send-keys -t $SID:$WID T
if [[ "$CMD" =~ "elinks" ]]; then
    tmux send-keys -t $SID:$WID o
fi
tmux set-buffer "$URI"
tmux paste-buffer -t $SID:$WID
tmux send-keys -t $SID:$WID C-m

exit 0
