#! /bin/bash

if [ -z "$DISPLAY" ]; then
    SID=0
else
    SID=1
fi

WID=8
WIN="web"

#CMD="cd ~; TERM=jfbterm w3m -s"
CMD="cd ~/temp; w3m -s"

while getopts "e" opt; do
    case $opt in
        e) 
           CMD="elinks"
           ;;
        ?) echo 'Usage0: wemux [-e] URI'
           exit 1;;
    esac
done

shift $((OPTIND-1))  #This tells getopts to move on to the next argument.

if [ $# -gt 1 ]; then
    echo 'Usage1: wemux [-e] URI'
    exit 1
fi

tmux has-session -t $SID
if [ $? -ne 0 ]; then
    if [ -z "$1" ]; then
        $CMD .
    else
        $CMD "$1"
    fi

    exit 0
fi

URI="."
if [ ! -z "$1" ]; then
    if [ -f "$1" ] || [ -d "$1" ]; then
        URI=$(realpath -s "$1")
        URI="file://${URI}"
    else
        #if [ "${1:0:3}" = "www" ]; then
        #    URI="http://"${1}
        #fi
        URI="http://"${1}
    fi
fi

tmux select-window -t $SID:$WIN > /dev/null 2>&1
if [ $? -ne 0 ]; then
    tmux new-window -n $WIN -t $SID:$WID "$CMD \"$URI\""
else
    tmux send-keys -t $SID:$WID T
    if [ "$CMD" = "elinks" ]; then
        tmux send-keys -t $SID:$WID o
    fi
    tmux set-buffer "$URI"
    tmux paste-buffer -t $SID:$WID
    tmux send-keys -t $SID:$WID C-m
fi

exit 0
