#!/usr/bin/python3

#sudo apt-get install libxml2-dev libxslt1-dev
#pip install lxml

import shutil, os, sys, zipfile, tempfile
from lxml import etree

if len(sys.argv) == 1:
    print(f"Usage: {sys.argv[0]} <src.epub> <dst.txt>")
    exit(1)

srcFile = sys.argv[1]
dstFile = os.path.splitext(srcFile)[0]+'.txt'
if len(sys.argv) == 3:
    dstFile = sys.argv[2]

#print(f"src: {srcFile}")
#print(f"dst: {dstFile}")

with tempfile.TemporaryDirectory() as tmpDir:
    #print(f"Extracting input to temp directory '{tmpDir}'")
    with zipfile.ZipFile(srcFile, 'r') as zip_ref:
        zip_ref.extractall(tmpDir)

    with open(dstFile, "w") as outFile:
        #print(f"Parsing 'container.xml' file")
        containerFilePath = f"{tmpDir}/META-INF/container.xml"
        tree = etree.parse(containerFilePath)
        for rootFile in tree.xpath("//*[local-name()='container']"
                                   "/*[local-name()='rootfiles']"
                                   "/*[local-name()='rootfile']"
                                   "/@full-path"):
            #print(f"Parsing '{rootFile}' file")
            contentFilePath = f"{tmpDir}/{rootFile}"
            contentFileDir = os.path.dirname(contentFilePath)

            tree = etree.parse(contentFilePath)
            for idref in tree.xpath("//*[local-name()='package']"
                                    "/*[local-name()='spine']"
                                    "/*[local-name()='itemref']"
                                    "/@idref"):
                for href in tree.xpath(f"//*[local-name()='package']"
                                       f"/*[local-name()='manifest']"
                                       f"/*[local-name()='item'][@id='{idref}']"
                                       f"/@href"):
                    outFile.write("\n")
                    xhtmlFilePath = f"{contentFileDir}/{href}"
                    subtree = etree.parse(xhtmlFilePath, etree.HTMLParser())
                    for ptag in subtree.xpath("//html/body/*"):
                        for text in ptag.itertext():
                            outFile.write(f"{text}")
                        outFile.write("\n")

#print(f"Text written to '{dstFile}'")
